[2024-07-20_11:27:39] - [x_test_runner_send_main.py:137] INFO main start...
[2024-07-20_11:27:40] - [x_test_runner_send_main.py:114] INFO 报告路径：D:\mytest\UnittestDemo\report\result-20240720.html
[2024-07-20_11:30:40] - [x_test_runner_send_main.py:137] INFO main start...
[2024-07-20_11:30:40] - [x_test_runner_send_main.py:114] INFO 报告路径：D:\mytest\UnittestDemo\report\result-20240720.html
[2024-07-20_14:41:31] - [x_test_runner_send_main.py:137] INFO main start...
[2024-07-20_14:41:31] - [x_test_runner_send_main.py:114] INFO 报告路径：D:\mytest\UnittestDemo\report\result-20240720.html
[2024-07-20_14:51:40] - [x_test_runner_send_main.py:137] INFO main start...
[2024-07-20_14:51:40] - [x_test_runner_send_main.py:114] INFO 报告路径：D:\mytest\UnittestDemo\report\result-20240720.html
[2024-07-20_14:51:56] - [x_test_runner_send_main.py:137] INFO main start...
[2024-07-20_14:51:57] - [x_test_runner_send_main.py:114] INFO 报告路径：D:\mytest\UnittestDemo\report\result-20240720.html
[2024-07-20_14:52:30] - [x_test_runner_send_main.py:137] INFO main start...
[2024-07-20_14:52:31] - [x_test_runner_send_main.py:114] INFO 报告路径：D:\mytest\UnittestDemo\report\result-20240720.html
[2024-07-20_15:02:58] - [x_test_runner_send_main.py:137] INFO main start...
[2024-07-20_15:02:58] - [x_test_runner_send_main.py:114] INFO 报告路径：D:\mytest\UnittestDemo\report\result-20240720.html
[2024-07-20_16:33:31] - [x_test_runner_send_main.py:137] INFO main start...
[2024-07-20_16:33:31] - [test_dvd.py:42] INFO 开始执行用例：正确用户名，密码
[2024-07-20_16:33:32] - [x_test_runner_send_main.py:43] ERROR test_login_1 (test_dvd.TestDvd.test_login_1)
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 589, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\ddt.py", line 221, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mytest\UnittestDemo\testcase\test_dvd.py", line 50, in test_login
    self.assertIn(str(body), res.text)
AssertionError: '2001' not found in '{"code":200,"response":"kr9at%2bpDrRHEoabF%2bGeoIP5pbI55%2f9ASDBsxc9iN3Wo%2f5HQ0mguq5zDFOvD%2br7edy%2fpJshSdnJ3WLZKxEL2AAmxIO258LljcS%2fGIeWBx%2bzvY%2bMnFcOxkF1MJBgUieROdPN8iFG107CKoNhwVxDz%2fela9ubal74%2f7FZSLNgdUAHlw9D4Rd4%2fkySb2025olETj","current_time":"2024-07-20 16:33:32"}'
[2024-07-20_16:33:32] - [test_dvd.py:52] WARNING File "D:\mytest\UnittestDemo\testcase\test_dvd.py", line 1 不执行：错误的用户名
[2024-07-20_16:33:32] - [test_dvd.py:52] WARNING File "D:\mytest\UnittestDemo\testcase\test_dvd.py", line 1 不执行：错误的密码
[2024-07-20_16:33:32] - [x_test_runner_send_main.py:48] CRITICAL test_excel_api (unittest.loader._FailedTest.test_excel_api)
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 589, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\loader.py", line 33, in testFailure
    raise self._exception
ImportError: Failed to import test module: test_excel_api
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\loader.py", line 396, in _find_test_path
    module = self._get_module_from_name(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\loader.py", line 339, in _get_module_from_name
    __import__(name)
  File "D:\mytest\UnittestDemo\testcase\test_excel_api.py", line 13, in <module>
    from utils.xlrd_excel import XlrdExcel
  File "D:\mytest\UnittestDemo\utils\xlrd_excel.py", line 5, in <module>
    import xlrd
ModuleNotFoundError: No module named 'xlrd'

[2024-07-20_16:33:32] - [x_test_runner_send_main.py:114] INFO 报告路径：D:\mytest\UnittestDemo\report\result-20240720.html
[2024-07-20_16:34:04] - [x_test_runner_send_main.py:137] INFO main start...
[2024-07-20_16:34:04] - [test_dvd.py:42] INFO 开始执行用例：正确用户名，密码
[2024-07-20_16:34:04] - [x_test_runner_send_main.py:43] ERROR test_login_1 (test_dvd.TestDvd.test_login_1)
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 589, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\ddt.py", line 221, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mytest\UnittestDemo\testcase\test_dvd.py", line 50, in test_login
    self.assertIn(str(body), res.text)
AssertionError: '2001' not found in '{"code":200,"response":"kr9at%2bpDrRHEoabF%2bGeoIP5pbI55%2f9ASDBsxc9iN3Wo%2f5HQ0mguq5zDFOvD%2br7edy%2fpJshSdnJ3WLZKxEL2AAmxIO258LljcS%2fGIeWBx%2bzvY%2bMnFcOxkF1MJBgUieROdPN8iFG107CKoNhwVxDz%2fela9ubal74%2f7FZSLNgdUAHlw9D4Rd4%2fkySb2025olETj","current_time":"2024-07-20 16:34:05"}'
[2024-07-20_16:34:04] - [test_dvd.py:52] WARNING File "D:\mytest\UnittestDemo\testcase\test_dvd.py", line 1 不执行：错误的用户名
[2024-07-20_16:34:04] - [test_dvd.py:52] WARNING File "D:\mytest\UnittestDemo\testcase\test_dvd.py", line 1 不执行：错误的密码
[2024-07-20_16:34:04] - [test_excel_api.py:104] INFO 响应数据：{"msg":"操作成功","img":"/9j/4AAQSkZJRgABAgAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAA8AKADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDtrW1ga1hZoIySikkoOeKsCztv+feL/vgU2z/484P+ua/yqyKiMY8q0IjGPKtCIWdr/wA+0P8A3wKeLK1/59of+/YqUU4cU+WPYfLHsRCytP8An1h/79inCxtP+fWD/v2Kzdb8TaX4et/N1C5EefuxqNzt9AKz/DXj7SfEt3Ja2wkhmUblSYAFh7Y4z7V0xwFadJ1403yLrbQXuXsdKLCz/wCfWD/v2KcLCz/59IP+/YqXeqqWYgKBkkngU21uoLyBZ7aZJYmztdGyDg4OD9RXPyK17D5Y9gGn2X/Ppb/9+x/hThp1l/z52/8A36X/AAomvLa1GZ54ov8AfcL/ADrn7/4ieGdOuBBJqccshOD5PzhfqRxWtLCVKztSg5PyVxNQW50Y06x/587f/v0v+FOGm2P/AD5W/wD36X/CnW1xFdQRzQuHjkUMrDoQasCsnBLRofLHsVxplh/z5W3/AH6X/CnjTLD/AJ8bb/v0v+FWBUVze21lGZLm4ihQDJaRwo/WhQTdkg5Y9hBpen/8+Nt/35X/AAp40rT/APnwtf8Avyv+FcFqPxk8O2V55FslzeKpw80SYRfxPJ/Ku60jV7PWtOhv7GUS28y7lbGPzHY1018vr0IKdWm4p7XQlyPREo0rTv8Anwtf+/K/4U4aTp3/AED7X/vyv+FWhTxXLyx7D5Y9iqNJ03/oH2n/AH5X/Cq2p6Xp8ekXrpY2qusDlWEKgg7TyOK1hVXVv+QLf/8AXvJ/6CaUox5XoKUY8r0OSs/+POD/AK5r/KrIqvZ/8ecH/XNf5VZFOPwocfhQ4VieKNQubDQbyazGblYyUHvW2BxWLrsDyWzbfStISUZKTV7FM8X0HVLSW8nvNXf7Resfkef5gB7Z70/w08k/jdNQtU2QrKWOOBt6YrO1qzgGtm1iTY+75yOn5VPp1zd+HLmOdlM1kzYcAdP8DX3tWpTqwlKg7VK0PdhLZR293prbRHKk1vsmela74lubtrzQptPlWC4QRxXQGV57t7VX8M3V3JrcFvHq9sLPTlMKWcRyX45Y/X9KraxaHxLpFu1jegW7EOcDIcDsfxrW0Lw9bQ6qdQWDbcMNpb+tfM/WKNLDum1aTTTVr2eiu77Nq+23zNrNu5c8WaFp+vSw3F6srPChVdjlRg815V4s03T7F7aCwg8uRicjcWJ/OvctVtZG0yYQMEnMZ8t2GQGxwSPTNeLXug64L1ry4vIWvO20ZA9hxXTkeNnSmnUr8sI7Rbdm3fsmrX3ZNWN1oj2LwK0sPhyxtpiS8cQU5rsAeK8J0HxjrE1l9jsWhi1q1kz5MwGy5QZ3Lz0YcHqOhrXl8VePtWT7NHaWekqeHuSckfTJP8vxFctfK66qydacYu93eVt9bpbtPpZP7ylNW0PX3cKpNeSfEPTrrWfFmlboZZNOVCs+xsAc55/SotH0K+t9YgvE8XXVzeRuGlhlYlZV7qRuJAx3wfpXf3Oni4HmEVzxqrA1lUw81J2etmrXTXW3qmO3MrNHlXi64tNN8ONYw2sMKSfLGiIBg+v1966D4LXs6aTdW0hbyhNujz05HP8AKuL+IAaTxfBayBhbxouOOME8n9P0r1PwTpf2SBFRNqDoBXp4uoqGVwoy96VV87fb/gkRV5t9j0RDlRUgqOMYUVKK+cNhwqrq3/IEv/8Ar2k/9BNWxVXV/wDkCX//AF7Sf+gmpl8LJl8LOSs/+PKD/rmv8qsiq9l/x5Qf9c1/lVkUR+FBH4UOFVr2MPA3HarQodN6kVRR4b4t8PTvrBvbIgSEjcp45HcVmve39paPDqOmb4WXa7p0/wAK9l1HQluGLAc1z974cl2kKDXrU82lyQp1oKahs9VJejTM3T1umcP8OL2ZNeawBZ7SVSSD/CR0Ne52dmiKCBXCeH/DpsrvzFiVSe4GK9GtkKxgH0rLNMdDG4h14Q5bpX9e44R5VYjurYSREV5d4wnudNvWgttIuLlmUMsy/c/l1HpXrjLla53V9NkugQO9clCpCnPmnHmXZ3X5FNX2Pnd/7QTVRd+TJFPvDjA6Guyey8Q6q+1tTEFk4B+RcPgjpx+XWutHg9zcbyvfNdJY+GwiAMK9bFZ5OvySVOKcVZaX9LXvt0M40kup5rD4CsCAY7m8iuByswcZB9elei+D4tbtbGay1e7S+RTm3uQfnK91cHuPXJ69eK2l0GMD7tX7TTxDwK4K2YYivDkrS5vXVr0e69Ni1BLY4Dxfp2opbS3OmKjXUZ3BGXO8DqPrV/4beKP7YjnsL+1+x6pa4LwlSu5D0YA8jngj6etdXqOnmZPlHNU9O0wR3aTPEhljyEcr8yg9cGs4VqaoOlKCb3Uuq8vNBZ3vc6teRTxUcWdoqUVzFDhVXV/+QJf/APXtJ/6Catiqur/8gS//AOvaT/0E1MvhZMvhZyVl/wAeVv8A9c1/lVkVzMWtXMUSRqkRCKFGQe341J/b91/zzh/75P8AjWUa0bIzjVjZHSinCuZ/4SG7/wCecH/fJ/xpf+Eiu/8AnnB/3yf8ar20R+2idPtBpDAjdQK5r/hJLz/nlB/3yf8AGl/4SW8/55Qf98n/ABo9tEPbROljtkQ5CirKjFcl/wAJPe/88rf/AL5b/Gl/4Si9/wCeVv8A98t/jR7aIe2ideBS+WrdRXIf8JVff88rf/vlv8aX/hK77/nlbf8AfLf40e2iHtonXCBPQVMqAdq4z/hLb/8A5423/fLf40v/AAl+of8APG2/75b/AOKo9tEPbRO2Ap4FcP8A8JhqH/PG1/75b/4ql/4TLUf+eNr/AN8t/wDFUe2iHtoncbAetKsKg9K4f/hM9R/542v/AHw3/wAVS/8ACa6l/wA8LT/vhv8A4qj20Q9tE71RiniuA/4TbUv+eFp/3w3/AMVS/wDCcan/AM8LT/vhv/iqPbRD20T0EVV1f/kB6h/17Sf+gmuK/wCE51P/AJ4Wn/fDf/FVHc+M9RurWa3eG1CSoyMVVsgEY4+aplWjZilVjZn/2Q==","code":200,"captchaEnabled":true,"uuid":"192f5b8689814975a0c36fe9a95f9818"}
[2024-07-20_16:34:04] - [test_excel_api.py:104] INFO 响应数据：{"code":200,"msg":"Success","data":[]}
[2024-07-20_16:34:04] - [x_test_runner_send_main.py:114] INFO 报告路径：D:\mytest\UnittestDemo\report\result-20240720.html
[2024-07-20_16:37:15] - [x_test_runner_send_main.py:137] INFO main start...
[2024-07-20_16:37:15] - [x_test_runner_send_main.py:48] CRITICAL test_api_0 (seldom_test_excel_api.TestAPI.test_api_0)
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 589, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\seldom\extend_lib\parameterized.py", line 619, in standalone_func
    return func(*(a + p.args), **p.kwargs, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TestAPI.test_api() takes 3 positional arguments but 14 were given
[2024-07-20_16:37:15] - [x_test_runner_send_main.py:48] CRITICAL test_api_1 (seldom_test_excel_api.TestAPI.test_api_1)
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 589, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\seldom\extend_lib\parameterized.py", line 619, in standalone_func
    return func(*(a + p.args), **p.kwargs, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TestAPI.test_api() takes 3 positional arguments but 13 were given
[2024-07-20_16:37:15] - [x_test_runner_send_main.py:114] INFO 报告路径：D:\mytest\UnittestDemo\report\result-20240720.html
[2024-07-20_16:37:41] - [x_test_runner_send_main.py:137] INFO main start...
[2024-07-20_16:37:42] - [x_test_runner_send_main.py:48] CRITICAL test_api_0 (seldom_test_excel_api.TestAPI.test_api_0)
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 589, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\seldom\extend_lib\parameterized.py", line 619, in standalone_func
    return func(*(a + p.args), **p.kwargs, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TestAPI.test_api() takes 2 positional arguments but 14 were given
[2024-07-20_16:37:42] - [x_test_runner_send_main.py:48] CRITICAL test_api_1 (seldom_test_excel_api.TestAPI.test_api_1)
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 589, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\seldom\extend_lib\parameterized.py", line 619, in standalone_func
    return func(*(a + p.args), **p.kwargs, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TestAPI.test_api() takes 2 positional arguments but 13 were given
[2024-07-20_16:37:42] - [x_test_runner_send_main.py:114] INFO 报告路径：D:\mytest\UnittestDemo\report\result-20240720.html
[2024-07-20_16:38:18] - [x_test_runner_send_main.py:137] INFO main start...
[2024-07-20_16:38:19] - [x_test_runner_send_main.py:114] INFO 报告路径：D:\mytest\UnittestDemo\report\result-20240720.html
[2024-07-20_16:40:08] - [x_test_runner_send_main.py:137] INFO main start...
[2024-07-20_16:40:09] - [x_test_runner_send_main.py:114] INFO 报告路径：D:\mytest\UnittestDemo\report\result-20240720.html
[2024-07-20_16:41:07] - [x_test_runner_send_main.py:137] INFO main start...
[2024-07-20_16:41:07] - [seldom_test_excel_api.py:26] WARNING {'id': 'lqc_1', 'title': '获取base64验证码', 'url': 'http://192.168.50.202:9999/test-api/code', 'method': 'get', 'headers': None, 'body': None, 'code': '200', 'msg': '操作成功', 'result': 'PASS', 'tester': 'Jason', None: None, 'row_number': 2, 'sheet_name': 'Sheet1'}
[2024-07-20_16:41:07] - [seldom_test_excel_api.py:26] WARNING {'id': 'lqc_2', 'casetitle': '多个sheet页执行用例', 'url': 'https://admin.liqicloud.com/prod-api/qiyelibrary/crm/project/reportable', 'method': 'post', 'headers': '{"Content-Type":"application/x-www-form-urlencoded"}', 'body': 'projectId=91110108783249629Y&sign=c5a01e1219c2749589cc19a320fd8f2d', 'code': '200', 'msg': 'Success', 'result': 'PASS', 'tester': 'Jason', 'row_number': 2, 'sheet_name': 'Sheet2'}
[2024-07-20_16:41:07] - [x_test_runner_send_main.py:114] INFO 报告路径：D:\mytest\UnittestDemo\report\result-20240720.html
