[2024-10-21_14:03:46] - [run_x_test_runner_send_main.py:251] INFO main start...
[2024-10-21_14:03:46] - [run_x_test_runner_send_main.py:61] CRITICAL setUpClass (test_excel_api.TestAPI)
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\suite.py", line 166, in _handleClassSetUp
    setUpClass()
  File "D:\mytest\UnittestDemo\testcase\test_excel_api.py", line 59, in setUpClass
    cls.headers = utils.verification_code_login.main()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'utils' has no attribute 'verification_code_login'
[2024-10-21_14:03:46] - [run_x_test_runner_send_main.py:130] INFO 报告路径：D:\mytest\UnittestDemo\reports\result-20241021.html
[2024-10-21_14:04:52] - [run_x_test_runner_send_main.py:251] INFO main start...
[2024-10-21_14:04:54] - [connectionpool.py:243] DEBUG Starting new HTTP connection (1): 192.168.50.202:9999
[2024-10-21_14:04:54] - [connectionpool.py:546] DEBUG http://192.168.50.202:9999 "GET /test-api/code HTTP/11" 200 3934
[2024-10-21_14:04:54] - [connectionpool.py:1051] DEBUG Starting new HTTPS connection (1): aip.baidubce.com:443
[2024-10-21_14:04:54] - [connectionpool.py:546] DEBUG https://aip.baidubce.com:443 "GET /oauth/2.0/token?grant_type=client_credentials&client_id=BjvIG8O9uXLOXWGcpBB3CTZ6&client_secret=q7NLp5cZ4DzHGt057Sc3gUJ8ClKZ5snK HTTP/11" 200 None
[2024-10-21_14:04:54] - [connectionpool.py:1051] DEBUG Starting new HTTPS connection (1): aip.baidubce.com:443
[2024-10-21_14:04:54] - [connectionpool.py:546] DEBUG https://aip.baidubce.com:443 "POST /rest/2.0/ocr/v1/general_basic?access_token=24.b231b575f8d63bb2971fc8a54c50d532.2592000.1732082695.282335-115896386&aipSdk=python&aipVersion=4.15.13 HTTP/11" 200 85
[2024-10-21_14:04:54] - [verification_code_login.py:206] DEBUG 验证码文本：5
[2024-10-21_14:04:54] - [verification_code_login.py:208] DEBUG 验证码计算结果：None
[2024-10-21_14:04:54] - [connectionpool.py:546] DEBUG http://192.168.50.202:9999 "POST /test-api/auth/login HTTP/11" 200 42
[2024-10-21_14:04:54] - [verification_code_login.py:210] DEBUG 登录结果：{'code': 500, 'msg': '验证码不能为空'}
[2024-10-21_14:04:54] - [connectionpool.py:546] DEBUG http://192.168.50.202:9999 "GET /test-api/code HTTP/11" 200 4146
[2024-10-21_14:04:54] - [connectionpool.py:1051] DEBUG Starting new HTTPS connection (1): aip.baidubce.com:443
[2024-10-21_14:04:55] - [connectionpool.py:546] DEBUG https://aip.baidubce.com:443 "GET /oauth/2.0/token?grant_type=client_credentials&client_id=BjvIG8O9uXLOXWGcpBB3CTZ6&client_secret=q7NLp5cZ4DzHGt057Sc3gUJ8ClKZ5snK HTTP/11" 200 None
[2024-10-21_14:04:55] - [connectionpool.py:1051] DEBUG Starting new HTTPS connection (1): aip.baidubce.com:443
[2024-10-21_14:04:55] - [connectionpool.py:546] DEBUG https://aip.baidubce.com:443 "POST /rest/2.0/ocr/v1/general_basic?access_token=24.e2721c685a4e854c60a9a1a5267075b4.2592000.1732082696.282335-115896386&aipSdk=python&aipVersion=4.15.13 HTTP/11" 200 86
[2024-10-21_14:04:55] - [verification_code_login.py:206] DEBUG 验证码文本：5+
[2024-10-21_14:04:55] - [verification_code_login.py:208] DEBUG 验证码计算结果：None
[2024-10-21_14:04:55] - [connectionpool.py:546] DEBUG http://192.168.50.202:9999 "POST /test-api/auth/login HTTP/11" 200 42
[2024-10-21_14:04:55] - [verification_code_login.py:210] DEBUG 登录结果：{'code': 500, 'msg': '验证码不能为空'}
[2024-10-21_14:04:55] - [connectionpool.py:546] DEBUG http://192.168.50.202:9999 "GET /test-api/code HTTP/11" 200 3958
[2024-10-21_14:04:55] - [connectionpool.py:1051] DEBUG Starting new HTTPS connection (1): aip.baidubce.com:443
[2024-10-21_14:04:55] - [connectionpool.py:546] DEBUG https://aip.baidubce.com:443 "GET /oauth/2.0/token?grant_type=client_credentials&client_id=BjvIG8O9uXLOXWGcpBB3CTZ6&client_secret=q7NLp5cZ4DzHGt057Sc3gUJ8ClKZ5snK HTTP/11" 200 None
[2024-10-21_14:04:55] - [connectionpool.py:1051] DEBUG Starting new HTTPS connection (1): aip.baidubce.com:443
[2024-10-21_14:04:56] - [connectionpool.py:546] DEBUG https://aip.baidubce.com:443 "POST /rest/2.0/ocr/v1/general_basic?access_token=24.e2721c685a4e854c60a9a1a5267075b4.2592000.1732082696.282335-115896386&aipSdk=python&aipVersion=4.15.13 HTTP/11" 200 91
[2024-10-21_14:04:56] - [verification_code_login.py:206] DEBUG 验证码文本：3*2≈
[2024-10-21_14:04:56] - [verification_code_login.py:208] DEBUG 验证码计算结果：6
[2024-10-21_14:04:56] - [connectionpool.py:546] DEBUG http://192.168.50.202:9999 "POST /test-api/auth/login HTTP/11" 200 None
[2024-10-21_14:04:56] - [verification_code_login.py:210] DEBUG 登录结果：{'code': 200, 'msg': 'Success', 'data': {'access_token': 'eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyRGVwdElkIjoxMDMsInVzZXJfaWQiOjEsInVzZXJfa2V5IjoiZWExYTRjMGMtMGFiOC00YjA4LWEzM2QtMDdjYjk0ZDMwYTczIiwidXNlcm5hbWUiOiJhZG1pbiJ9.eC5aLTJH-vOlOMfcqXGf7XjLo3FjEZXbOARfi4ogkN61gdjUBqK-Fra08KNvNUecSNJc7e1i2X9TQOMZOejlOA', 'expires_in': 720}}
[2024-10-21_14:04:56] - [verification_code_login.py:257] INFO 登录成功token：{'Content-Type': 'application/json;charset=utf-8', 'authorization': 'Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyRGVwdElkIjoxMDMsInVzZXJfaWQiOjEsInVzZXJfa2V5IjoiZWExYTRjMGMtMGFiOC00YjA4LWEzM2QtMDdjYjk0ZDMwYTczIiwidXNlcm5hbWUiOiJhZG1pbiJ9.eC5aLTJH-vOlOMfcqXGf7XjLo3FjEZXbOARfi4ogkN61gdjUBqK-Fra08KNvNUecSNJc7e1i2X9TQOMZOejlOA'}
[2024-10-21_14:04:56] - [connectionpool.py:1051] DEBUG Starting new HTTPS connection (1): test-lqc-api.liqicloud.com:443
[2024-10-21_14:04:56] - [connectionpool.py:546] DEBUG https://test-lqc-api.liqicloud.com:443 "POST /app/applet/project/list HTTP/11" 200 None
[2024-10-21_14:04:56] - [test_excel_api.py:169] DEBUG 用例数据：{'id': 'lqc_1', 'title': '查询2024年1月深圳市项目', 'url': 'https://test-lqc-api.liqicloud.com/app/applet/project/list', 'method': 'post', 'headers': '{"Content-Type":"application/json;charset=utf-8", "authorization":"eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyX2lkIjoxODQwNjc4OTQ0MzQwMzgxNjk3fQ.aeyslq073lFygeQBHqUjm4IiIhPahN6vk8N0kgtsncJpuAj0HsoatuefzsvGSIyxvp4bwpv74IsCgr42-hT_KA"}', 'body': '{"pageSize":15,"pageNo":1,"deptCategoryIdList":[],"rank":0,"years":2024,"month":1,"policyName":"测试"}', 'code': None, 'msg': '测试2024年1月深圳市项目', 'result': 'PASS', 'variable': None, 'delay': None, 'row_number': 2, 'sheet_name': 'Sheet1'}
[2024-10-21_14:04:56] - [test_excel_api.py:170] INFO https://test-lqc-api.liqicloud.com/app/applet/project/list 响应数据：{"code":200,"msg":"Success","data":{"page":1,"size":15,"total":1,"list":[{"id":"1846813020097077250","name":"测试2024年1月深圳市项目","deptName":"深圳市龙岗政府在线","officialPublishTime":"2024-01-01 00:00:00","reportDeadLine":null}]}}
[2024-10-21_14:04:56] - [connectionpool.py:1051] DEBUG Starting new HTTPS connection (1): test-lqc-api.liqicloud.com:443
[2024-10-21_14:04:56] - [connectionpool.py:546] DEBUG https://test-lqc-api.liqicloud.com:443 "POST /app/applet/project/list HTTP/11" 200 None
[2024-10-21_14:04:56] - [test_excel_api.py:169] DEBUG 用例数据：{'id': 'lqc_2', 'title': '查询2023年深圳市市级项目', 'url': 'https://test-lqc-api.liqicloud.com/app/applet/project/list', 'method': 'post', 'headers': '{"Content-Type":"application/json;charset=utf-8", "authorization":"eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyX2lkIjoxODQwNjc4OTQ0MzQwMzgxNjk3fQ.aeyslq073lFygeQBHqUjm4IiIhPahN6vk8N0kgtsncJpuAj0HsoatuefzsvGSIyxvp4bwpv74IsCgr42-hT_KA"}', 'body': '{"pageSize":15,"pageNo":1,"deptCategoryIdList":[],"rank":0,"years":2023,"month":10,"policyName":"测试","provinceCode":"440000","cityCode":"440300"}', 'code': None, 'msg': '测试2023年深圳市市级项目', 'result': 'PASS', 'variable': None, 'delay': None, 'row_number': 3, 'sheet_name': 'Sheet1'}
[2024-10-21_14:04:56] - [test_excel_api.py:170] INFO https://test-lqc-api.liqicloud.com/app/applet/project/list 响应数据：{"code":200,"msg":"Success","data":{"page":1,"size":15,"total":1,"list":[{"id":"1846813577784320002","name":"测试2023年深圳市市级项目","deptName":"深圳市发展和改革委员会","officialPublishTime":"2023-10-01 00:00:00","reportDeadLine":null}]}}
[2024-10-21_14:04:56] - [connectionpool.py:1051] DEBUG Starting new HTTPS connection (1): test-lqc-api.liqicloud.com:443
[2024-10-21_14:04:56] - [connectionpool.py:546] DEBUG https://test-lqc-api.liqicloud.com:443 "POST /app/applet/public/list HTTP/11" 200 None
[2024-10-21_14:04:56] - [test_excel_api.py:169] DEBUG 用例数据：{'id': 'lqc_3', 'title': '查询全部公示', 'url': 'https://test-lqc-api.liqicloud.com/app/applet/public/list', 'method': 'post', 'headers': '{"Content-Type":"application/json;charset=utf-8", "authorization":"eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyX2lkIjoxODQwNjc4OTQ0MzQwMzgxNjk3fQ.aeyslq073lFygeQBHqUjm4IiIhPahN6vk8N0kgtsncJpuAj0HsoatuefzsvGSIyxvp4bwpv74IsCgr42-hT_KA"}', 'body': '{"pageSize":15,"pageNo":1,"deptCategoryIdList":[],"rank":0,"years":0,"month":0,"provinceCode":"440000","cityCode":"440300"}', 'code': None, 'msg': '测试公示', 'result': 'PASS', 'variable': None, 'delay': None, 'row_number': 4, 'sheet_name': 'Sheet1'}
[2024-10-21_14:04:56] - [test_excel_api.py:170] INFO https://test-lqc-api.liqicloud.com/app/applet/public/list 响应数据：{"code":200,"msg":"Success","data":{"page":1,"size":15,"total":17,"list":[{"id":"1829424338901893122","name":"新增测试公示1","deptName":"工信经济测试","officialPublishTime":"2024-08-30 15:18:59"},{"id":"1826550431404634114","name":"深圳公示14","deptName":"测试知识","officialPublishTime":"2024-08-22 17:22:11"},{"id":"1792377649850699777","name":"测试关于新型冠状病毒疫情防控期间延长我市社会保险缴费工作的通告","deptName":"测试认证认可部门12","officialPublishTime":"2024-08-12 14:20:02"},{"id":"1791676620159000577","name":"0812工信关于做好2020年度专业技术人员继续教育项目计划备案的通知","deptName":"深圳市龙岗政府在线","officialPublishTime":"2024-08-09 00:00:00"},{"id":"1821809302314389506","name":"广州公示0809","deptName":"工信经济测试","officialPublishTime":"2024-08-09 00:00:00"},{"id":"1791001276800262146","name":"关于开展青岛市2021年第二次博士后资助申报工作的通知","deptName":"深圳市龙岗政府在线","officialPublishTime":"2024-08-05 00:00:00"},{"id":"1821792987881213954","name":"关于鼓励企业开展岗前技能培训工作的通知","deptName":"福田区企业服务智能系统平台","officialPublishTime":"2024-08-03 00:00:00"},{"id":"1791001052484689922","name":"关于做好2022年国家级博士后科研工作站新设站（第二批）申报工作的通知","deptName":"光明区企业服务门户","officialPublishTime":"2024-07-17 00:00:00"},{"id":"1797512470608441345","name":"笔试成绩1","deptName":"福田区企业服务智能系统平台","officialPublishTime":"2024-06-26 00:00:00"},{"id":"1797468996995608578","name":"新增公示","deptName":"光明区企业服务门户","officialPublishTime":"2024-06-03 11:22:53"},{"id":"1790928470779584514","name":"test1公式新增2","deptName":"深圳市龙岗政府在线","officialPublishTime":"2024-05-16 10:13:05"},{"id":"1790631237412675585","name":"审核无效4","deptName":"光明区企业服务门户","officialPublishTime":"2024-05-15 14:32:08"},{"id":"1790626839424884737","name":"公示行业","deptName":"光明区企业服务门户","officialPublishTime":"2024-05-15 14:14:07"},{"id":"1783700258106376193","name":"企业库测试1","deptName":"深圳市南山区发展与改革局","officialPublishTime":"2024-04-25 00:00:00"},{"id":"1778303714515456002","name":"test13","deptName":"光明区企业服务门户","officialPublishTime":"2024-04-11 14:05:12"}]}}
[2024-10-21_14:04:56] - [connectionpool.py:1051] DEBUG Starting new HTTPS connection (1): test-lqc-api.liqicloud.com:443
[2024-10-21_14:04:56] - [connectionpool.py:546] DEBUG https://test-lqc-api.liqicloud.com:443 "POST /app/applet/policy/list HTTP/11" 200 None
[2024-10-21_14:04:56] - [test_excel_api.py:169] DEBUG 用例数据：{'id': 'lqc_4', 'title': '查询2024年10月政策', 'url': 'https://test-lqc-api.liqicloud.com/app/applet/policy/list', 'method': 'post', 'headers': '{"Content-Type":"application/json;charset=utf-8", "authorization":"eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyX2lkIjoxODQwNjc4OTQ0MzQwMzgxNjk3fQ.aeyslq073lFygeQBHqUjm4IiIhPahN6vk8N0kgtsncJpuAj0HsoatuefzsvGSIyxvp4bwpv74IsCgr42-hT_KA"}', 'body': '{"pageSize":15,"pageNo":1,"deptCategoryIdList":[],"rank":0,"years":2024,"month":10,"provinceCode":"440000","cityCode":"440300"}', 'code': None, 'msg': '测试2024年10月政策', 'result': 'PASS', 'variable': None, 'delay': None, 'row_number': 5, 'sheet_name': 'Sheet1'}
[2024-10-21_14:04:56] - [test_excel_api.py:170] INFO https://test-lqc-api.liqicloud.com/app/applet/policy/list 响应数据：{"code":200,"msg":"Success","data":{"page":1,"size":15,"total":1,"list":[{"id":"1846814045096894465","policyName":"测试2024年10月政策","informationType":2,"deptName":"深圳市龙岗政府在线","officialPublishTime":"2024-10-01 00:00:00"}]}}
[2024-10-21_14:04:56] - [run_x_test_runner_send_main.py:61] CRITICAL test_api_05 (test_excel_api.TestAPI.test_api_05)
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 589, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\ddt.py", line 221, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mytest\UnittestDemo\testcase\test_excel_api.py", line 87, in test_api
    headers = ast.literal_eval(excel_data["headers"]) if excel_data["headers"] else eval(self.headers)
                                                                                    ^^^^^^^^^^^^^^^^^^
TypeError: eval() arg 1 must be a string, bytes or code object
[2024-10-21_14:04:56] - [run_x_test_runner_send_main.py:61] CRITICAL test_api_06 (test_excel_api.TestAPI.test_api_06)
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 589, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\ddt.py", line 221, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mytest\UnittestDemo\testcase\test_excel_api.py", line 87, in test_api
    headers = ast.literal_eval(excel_data["headers"]) if excel_data["headers"] else eval(self.headers)
                                                                                    ^^^^^^^^^^^^^^^^^^
TypeError: eval() arg 1 must be a string, bytes or code object
[2024-10-21_14:04:56] - [run_x_test_runner_send_main.py:61] CRITICAL test_api_07 (test_excel_api.TestAPI.test_api_07)
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 589, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\ddt.py", line 221, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mytest\UnittestDemo\testcase\test_excel_api.py", line 87, in test_api
    headers = ast.literal_eval(excel_data["headers"]) if excel_data["headers"] else eval(self.headers)
                                                                                    ^^^^^^^^^^^^^^^^^^
TypeError: eval() arg 1 must be a string, bytes or code object
[2024-10-21_14:04:56] - [run_x_test_runner_send_main.py:61] CRITICAL test_api_08 (test_excel_api.TestAPI.test_api_08)
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 589, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\ddt.py", line 221, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mytest\UnittestDemo\testcase\test_excel_api.py", line 87, in test_api
    headers = ast.literal_eval(excel_data["headers"]) if excel_data["headers"] else eval(self.headers)
                                                                                    ^^^^^^^^^^^^^^^^^^
TypeError: eval() arg 1 must be a string, bytes or code object
[2024-10-21_14:04:56] - [connectionpool.py:1051] DEBUG Starting new HTTPS connection (1): test-lqc-api.liqicloud.com:443
[2024-10-21_14:04:56] - [connectionpool.py:546] DEBUG https://test-lqc-api.liqicloud.com:443 "POST /app/applet/action/feedback/submit HTTP/11" 200 None
[2024-10-21_14:04:56] - [test_excel_api.py:169] DEBUG 用例数据：{'id': 'lqc_9', 'title': '问题反馈字段都为空', 'url': 'https://test-lqc-api.liqicloud.com/app/applet/action/feedback/submit', 'method': 'post', 'headers': '{"Content-Type":"application/json;charset=utf-8", "authorization":"eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyX2lkIjoxODQwNjc4OTQ0MzQwMzgxNjk3fQ.aeyslq073lFygeQBHqUjm4IiIhPahN6vk8N0kgtsncJpuAj0HsoatuefzsvGSIyxvp4bwpv74IsCgr42-hT_KA"}', 'body': '{"appUserId":"1840678944340381697","appUserName":"用户188****7806","appUserPhone":"18813537806","appUserSubmitName":"用户188****7806","submitIssueDescription":"","submitIssueType":"","uploadImageUrl":""}', 'code': None, 'msg': '"code":400', 'result': 'PASS', 'variable': None, 'delay': None, 'row_number': 10, 'sheet_name': 'Sheet1'}
[2024-10-21_14:04:56] - [test_excel_api.py:170] INFO https://test-lqc-api.liqicloud.com/app/applet/action/feedback/submit 响应数据：{"code":400,"msg":"反馈内容不能为空","data":null}
[2024-10-21_14:04:56] - [connectionpool.py:1051] DEBUG Starting new HTTPS connection (1): test-lqc-api.liqicloud.com:443
[2024-10-21_14:04:56] - [connectionpool.py:546] DEBUG https://test-lqc-api.liqicloud.com:443 "POST /app/applet/action/feedback/submit HTTP/11" 200 None
[2024-10-21_14:04:56] - [test_excel_api.py:169] DEBUG 用例数据：{'id': 'lqc_10', 'title': '问题反馈图片为空', 'url': 'https://test-lqc-api.liqicloud.com/app/applet/action/feedback/submit', 'method': 'post', 'headers': '{"Content-Type":"application/json;charset=utf-8", "authorization":"eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyX2lkIjoxODQwNjc4OTQ0MzQwMzgxNjk3fQ.aeyslq073lFygeQBHqUjm4IiIhPahN6vk8N0kgtsncJpuAj0HsoatuefzsvGSIyxvp4bwpv74IsCgr42-hT_KA"}', 'body': '{"appUserId":"1840678944340381697","appUserName":"用户188****7806","appUserPhone":"18813537806","appUserSubmitName":"用户188****7806","submitIssueDescription":"id","submitIssueType":1,"uploadImageUrl":""}', 'code': None, 'msg': '"code":400', 'result': 'PASS', 'variable': None, 'delay': None, 'row_number': 11, 'sheet_name': 'Sheet1'}
[2024-10-21_14:04:56] - [test_excel_api.py:170] INFO https://test-lqc-api.liqicloud.com/app/applet/action/feedback/submit 响应数据：{"code":400,"msg":"上传的图片不能为空","data":null}
[2024-10-21_14:04:56] - [connectionpool.py:1051] DEBUG Starting new HTTPS connection (1): test-lqc-api.liqicloud.com:443
[2024-10-21_14:04:56] - [connectionpool.py:546] DEBUG https://test-lqc-api.liqicloud.com:443 "POST /app/applet/action/feedback/submit HTTP/11" 200 None
[2024-10-21_14:04:56] - [test_excel_api.py:169] DEBUG 用例数据：{'id': 'lqc_11', 'title': '问题反馈内容为空', 'url': 'https://test-lqc-api.liqicloud.com/app/applet/action/feedback/submit', 'method': 'post', 'headers': '{"Content-Type":"application/json;charset=utf-8", "authorization":"eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyX2lkIjoxODQwNjc4OTQ0MzQwMzgxNjk3fQ.aeyslq073lFygeQBHqUjm4IiIhPahN6vk8N0kgtsncJpuAj0HsoatuefzsvGSIyxvp4bwpv74IsCgr42-hT_KA"}', 'body': '{"appUserId":"1840678944340381697","appUserName":"用户188****7806","appUserPhone":"18813537806","appUserSubmitName":"用户188****7806","submitIssueDescription":"","submitIssueType":1,"uploadImageUrl":"https://lqc-public-oss-pre.oss-cn-shenzhen.aliyuncs.com/test/lqc-app/c5c931dadc424b71a60326da53828fb6.jpg"}', 'code': None, 'msg': '"code":400', 'result': 'PASS', 'variable': None, 'delay': None, 'row_number': 12, 'sheet_name': 'Sheet1'}
[2024-10-21_14:04:56] - [test_excel_api.py:170] INFO https://test-lqc-api.liqicloud.com/app/applet/action/feedback/submit 响应数据：{"code":400,"msg":"反馈内容不能为空","data":null}
[2024-10-21_14:04:56] - [connectionpool.py:1051] DEBUG Starting new HTTPS connection (1): test-lqc-api.liqicloud.com:443
[2024-10-21_14:04:56] - [connectionpool.py:546] DEBUG https://test-lqc-api.liqicloud.com:443 "POST /app/applet/action/feedback/submit HTTP/11" 200 None
[2024-10-21_14:04:56] - [test_excel_api.py:169] DEBUG 用例数据：{'id': 'lqc_12', 'title': '问题反馈内容为超过200字符', 'url': 'https://test-lqc-api.liqicloud.com/app/applet/action/feedback/submit', 'method': 'post', 'headers': '{"Content-Type":"application/json;charset=utf-8", "authorization":"eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyX2lkIjoxODQwNjc4OTQ0MzQwMzgxNjk3fQ.aeyslq073lFygeQBHqUjm4IiIhPahN6vk8N0kgtsncJpuAj0HsoatuefzsvGSIyxvp4bwpv74IsCgr42-hT_KA"}', 'body': '{"appUserId":"1840678944340381697","appUserName":"用户188****7806","appUserPhone":"18813537806","appUserSubmitName":"用户188****7806","submitIssueDescription":"字段枚举值为：项目、政策资讯、通知文件、产业政策、公示、其他。其中项目、政策资讯、通知文件、产业政策、公示为由关键词配置自动识别的政策数据，‘其他’为未识别出的政策数据（即未击中关键词）识别为项目的政策数据，数据字段说明如下字段枚举值为：项目、政策资讯、通知文件、产业政策、公示、其他。其中项目、政策资讯、通知文件、产业政策、公示为由关键词配置自动识别的政策数据，‘其他’为未识别出的政策数据（即未击中关键词）识别为项目的政策数据，数据字段说明如下","submitIssueType":1,"uploadImageUrl":"https://lqc-public-oss-pre.oss-cn-shenzhen.aliyuncs.com/test/lqc-app/c5c931dadc424b71a60326da53828fb6.jpg"}', 'code': None, 'msg': '"code":400', 'result': 'PASS', 'variable': None, 'delay': None, 'row_number': 13, 'sheet_name': 'Sheet1'}
[2024-10-21_14:04:56] - [test_excel_api.py:170] INFO https://test-lqc-api.liqicloud.com/app/applet/action/feedback/submit 响应数据：{"code":400,"msg":"反馈内容字数不能超过200","data":null}
[2024-10-21_14:04:56] - [connectionpool.py:1051] DEBUG Starting new HTTPS connection (1): test-lqc-api.liqicloud.com:443
[2024-10-21_14:04:57] - [connectionpool.py:546] DEBUG https://test-lqc-api.liqicloud.com:443 "POST /app/applet/action/feedback/submit HTTP/11" 200 None
[2024-10-21_14:04:57] - [test_excel_api.py:169] DEBUG 用例数据：{'id': 'lqc_13', 'title': '问题反馈姓名为空', 'url': 'https://test-lqc-api.liqicloud.com/app/applet/action/feedback/submit', 'method': 'post', 'headers': '{"Content-Type":"application/json;charset=utf-8", "authorization":"eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyX2lkIjoxODQwNjc4OTQ0MzQwMzgxNjk3fQ.aeyslq073lFygeQBHqUjm4IiIhPahN6vk8N0kgtsncJpuAj0HsoatuefzsvGSIyxvp4bwpv74IsCgr42-hT_KA"}', 'body': '{"appUserId":"1840678944340381697","appUserName":"用户188****7806","appUserPhone":"18813537806","appUserSubmitName":"","submitIssueDescription":"id","submitIssueType":1,"uploadImageUrl":"https://lqc-public-oss-pre.oss-cn-shenzhen.aliyuncs.com/test/lqc-app/c5c931dadc424b71a60326da53828fb6.jpg"}', 'code': None, 'msg': '"code":400', 'result': 'PASS', 'variable': None, 'delay': None, 'row_number': 14, 'sheet_name': 'Sheet1'}
[2024-10-21_14:04:57] - [test_excel_api.py:170] INFO https://test-lqc-api.liqicloud.com/app/applet/action/feedback/submit 响应数据：{"code":400,"msg":"姓名不能为空","data":null}
[2024-10-21_14:04:57] - [connectionpool.py:1051] DEBUG Starting new HTTPS connection (1): test-lqc-api.liqicloud.com:443
[2024-10-21_14:04:57] - [connectionpool.py:546] DEBUG https://test-lqc-api.liqicloud.com:443 "POST /app/applet/action/feedback/submit HTTP/11" 200 None
[2024-10-21_14:04:57] - [test_excel_api.py:169] DEBUG 用例数据：{'id': 'lqc_14', 'title': '问题反馈联系方式错误的手机格式', 'url': 'https://test-lqc-api.liqicloud.com/app/applet/action/feedback/submit', 'method': 'post', 'headers': '{"Content-Type":"application/json;charset=utf-8", "authorization":"eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyX2lkIjoxODQwNjc4OTQ0MzQwMzgxNjk3fQ.aeyslq073lFygeQBHqUjm4IiIhPahN6vk8N0kgtsncJpuAj0HsoatuefzsvGSIyxvp4bwpv74IsCgr42-hT_KA"}', 'body': '{"appUserId":"1840678944340381697","appUserName":"用户188****7806","appUserPhone":"188135378061","appUserSubmitName":"","submitIssueDescription":"id","submitIssueType":1,"uploadImageUrl":"https://lqc-public-oss-pre.oss-cn-shenzhen.aliyuncs.com/test/lqc-app/c5c931dadc424b71a60326da53828fb6.jpg"}', 'code': None, 'msg': '"code":400', 'result': 'PASS', 'variable': None, 'delay': None, 'row_number': 15, 'sheet_name': 'Sheet1'}
[2024-10-21_14:04:57] - [test_excel_api.py:170] INFO https://test-lqc-api.liqicloud.com/app/applet/action/feedback/submit 响应数据：{"code":400,"msg":"联系方式格式不正确","data":null}
[2024-10-21_14:04:57] - [connectionpool.py:1051] DEBUG Starting new HTTPS connection (1): test-lqc-api.liqicloud.com:443
[2024-10-21_14:04:57] - [connectionpool.py:546] DEBUG https://test-lqc-api.liqicloud.com:443 "POST /app/applet/action/feedback/submit HTTP/11" 200 None
[2024-10-21_14:04:57] - [test_excel_api.py:169] DEBUG 用例数据：{'id': 'lqc_15', 'title': '新增正确的问题反馈', 'url': 'https://test-lqc-api.liqicloud.com/app/applet/action/feedback/submit', 'method': 'post', 'headers': '{"Content-Type":"application/json;charset=utf-8", "authorization":"eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyX2lkIjoxODQwNjc4OTQ0MzQwMzgxNjk3fQ.aeyslq073lFygeQBHqUjm4IiIhPahN6vk8N0kgtsncJpuAj0HsoatuefzsvGSIyxvp4bwpv74IsCgr42-hT_KA"}', 'body': '{"appUserId":"1840678944340381697","appUserName":"用户188****7806","appUserPhone":"18813537806","appUserSubmitName":"用户188****7806","submitIssueDescription":"测试反馈内容","submitIssueType":1,"uploadImageUrl":"https://lqc-public-oss-pre.oss-cn-shenzhen.aliyuncs.com/test/lqc-app/c5c931dadc424b71a60326da53828fb6.jpg"}', 'code': None, 'msg': '"code":200', 'result': 'PASS', 'variable': None, 'delay': None, 'row_number': 16, 'sheet_name': 'Sheet1'}
[2024-10-21_14:04:57] - [test_excel_api.py:170] INFO https://test-lqc-api.liqicloud.com/app/applet/action/feedback/submit 响应数据：{"code":200,"msg":null,"data":null}
[2024-10-21_14:04:57] - [connectionpool.py:1051] DEBUG Starting new HTTPS connection (1): test-lqc-api.liqicloud.com:443
[2024-10-21_14:04:57] - [connectionpool.py:546] DEBUG https://test-lqc-api.liqicloud.com:443 "GET /app/applet/action/feedback/list/1840678944340381697/1/15 HTTP/11" 200 None
[2024-10-21_14:04:57] - [test_excel_api.py:169] DEBUG 用例数据：{'id': 'lqc_16', 'title': '查询反馈记录', 'url': 'https://test-lqc-api.liqicloud.com/app/applet/action/feedback/list/1840678944340381697/1/15', 'method': None, 'headers': '{"Content-Type":"application/json;charset=utf-8", "authorization":"eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyX2lkIjoxODQwNjc4OTQ0MzQwMzgxNjk3fQ.aeyslq073lFygeQBHqUjm4IiIhPahN6vk8N0kgtsncJpuAj0HsoatuefzsvGSIyxvp4bwpv74IsCgr42-hT_KA"}', 'body': None, 'code': None, 'msg': '测试反馈内容', 'result': 'PASS', 'variable': None, 'delay': None, 'row_number': 17, 'sheet_name': 'Sheet1'}
[2024-10-21_14:04:57] - [test_excel_api.py:170] INFO https://test-lqc-api.liqicloud.com/app/applet/action/feedback/list/1840678944340381697/1/15 响应数据：{"code":200,"msg":"Success","data":{"page":1,"size":15,"total":5,"list":[{"id":"1848244063521959937","appUserId":"1840678944340381697","appUserName":"用户188****7806","appUserSubmitName":"用户188****7806","appUserPhone":"18813537806","submitIssueType":1,"submitIssueDescription":"测试反馈内容","submitIssueTime":"2024-10-21 14:04:58","uploadImageUrl":"https://lqc-public-oss-pre.oss-cn-shenzhen.aliyuncs.com/test/lqc-app/c5c931dadc424b71a60326da53828fb6.jpg","replyStatus":0,"replyText":null,"replyTime":null,"replyerName":"启程智远"},{"id":"1847543017367629825","appUserId":"1840678944340381697","appUserName":"用户188****7806","appUserSubmitName":"用户188****7806","appUserPhone":"18813537806","submitIssueType":1,"submitIssueDescription":"你看看吧，","submitIssueTime":"2024-10-19 15:39:15","uploadImageUrl":"https://lqc-public-oss-pre.oss-cn-shenzhen.aliyuncs.com/test/lqc-app/9efcddd7ff1a4f73993ff485bd423fb7.jpg","replyStatus":0,"replyText":null,"replyTime":null,"replyerName":"启程智远"},{"id":"1847542513581387777","appUserId":"1840678944340381697","appUserName":"用户188****7806","appUserSubmitName":"用户188****7806","appUserPhone":"18813537806","submitIssueType":2,"submitIssueDescription":"666","submitIssueTime":"2024-10-19 15:37:15","uploadImageUrl":"https://lqc-public-oss-pre.oss-cn-shenzhen.aliyuncs.com/test/lqc-app/fb74c2e9310a4f1788c397d9a756c509.jpg","replyStatus":1,"replyText":"&lt;textarea class=\"el-textarea__inner\" maxlength=\"300\" tabindex=\"0\" autocomplete=\"off\" placeholder=\"请输入回复内容\" id=\"el-id-9127","replyTime":"2024-10-19 15:37:51","replyerName":"启程智远"},{"id":"1846829897804431361","appUserId":"1840678944340381697","appUserName":"用户188****7806","appUserSubmitName":"用户188****7806","appUserPhone":"18813537806","submitIssueType":2,"submitIssueDescription":"你好啊","submitIssueTime":"2024-10-17 16:25:36","uploadImageUrl":"https://lqc-public-oss-pre.oss-cn-shenzhen.aliyuncs.com/test/lqc-app/07af737658234db3a8c56cbfad25615f.jpg,https://lqc-public-oss-pre.oss-cn-shenzhen.aliyuncs.com/test/lqc-app/601600986bd14571a9040503c9b3d448.jpg,https://lqc-public-oss-pre.oss-cn-shenzhen.aliyuncs.com/test/lqc-app/09386e440a234dde899ac65791f41791.jpg,https://lqc-public-oss-pre.oss-cn-shenzhen.aliyuncs.com/test/lqc-app/177da93adbca4714b47eb6afd1676999.jpg,https://lqc-public-oss-pre.oss-cn-shenzhen.aliyuncs.com/test/lqc-app/aa271c08225243369ff9d3fd8c60d9fc.jpg,https://lqc-public-oss-pre.oss-cn-shenzhen.aliyuncs.com/test/lqc-app/7a2e3e26c28c4350bc30e9d56232cf15.jpg,https://lqc-public-oss-pre.oss-cn-shenzhen.aliyuncs.com/test/lqc-app/3f7ad35ddfeb4f9dac7128e549807d80.jpeg","replyStatus":1,"replyText":"测试超过200字符公示为由关键词配置自动识别的政策数公示为由关键词配置自动识别的政策数公示为由关键词配置自动识别的政策数公示为由关键词配置自动识别的政策数公示为由关键词配置自动识别的政策数公示为由关键词配置自动识别的政策数公示为由关键词配置自动识别的政策数公示为由关键词配置自动识别的政策数公示为由关键词配置自动识别的政策数公示为由关键词配置自动识别的政策数公示为由关键词配置自动识别的政策数公示为由关键词配置自动识别的政策数","replyTime":"2024-10-18 09:59:18","replyerName":"启程智远"},{"id":"1846829608825274369","appUserId":"1840678944340381697","appUserName":"用户188****7806","appUserSubmitName":"用户188****7806","appUserPhone":"18813537806","submitIssueType":2,"submitIssueDescription":"你好啊","submitIssueTime":"2024-10-17 16:24:27","uploadImageUrl":"https://lqc-public-oss-pre.oss-cn-shenzhen.aliyuncs.com/test/lqc-app/07af737658234db3a8c56cbfad25615f.jpg,https://lqc-public-oss-pre.oss-cn-shenzhen.aliyuncs.com/test/lqc-app/601600986bd14571a9040503c9b3d448.jpg,https://lqc-public-oss-pre.oss-cn-shenzhen.aliyuncs.com/test/lqc-app/09386e440a234dde899ac65791f41791.jpg,https://lqc-public-oss-pre.oss-cn-shenzhen.aliyuncs.com/test/lqc-app/177da93adbca4714b47eb6afd1676999.jpg,https://lqc-public-oss-pre.oss-cn-shenzhen.aliyuncs.com/test/lqc-app/aa271c08225243369ff9d3fd8c60d9fc.jpg,https://lqc-public-oss-pre.oss-cn-shenzhen.aliyuncs.com/test/lqc-app/7a2e3e26c28c4350bc30e9d56232cf15.jpg","replyStatus":1,"replyText":"测试超过200字符公示为由关键词配置自动识别的政策数公示为由关键词配置自动识别的政策数公示为由关键词配置自动识别的政策数公示为由关键词配置自动识别的政策数公示为由关键词配置自动识别的政策数公示为由关键词配置自动识别的政策数公示为由关键词配置自动识别的政策数公示为由关键词配置自动识别的政策数公示为由关键词配置自动识别的政策数公示为由关键词配置自动识别的政策数公示为由关键词配置自动识别的政策数公示为由关键词配置自动识别的政策数","replyTime":"2024-10-18 11:45:55","replyerName":"启程智远"}]}}
[2024-10-21_14:04:57] - [run_x_test_runner_send_main.py:61] CRITICAL test_api_17 (test_excel_api.TestAPI.test_api_17)
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 589, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\ddt.py", line 221, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mytest\UnittestDemo\testcase\test_excel_api.py", line 87, in test_api
    headers = ast.literal_eval(excel_data["headers"]) if excel_data["headers"] else eval(self.headers)
                                                                                    ^^^^^^^^^^^^^^^^^^
TypeError: eval() arg 1 must be a string, bytes or code object
[2024-10-21_14:04:57] - [run_x_test_runner_send_main.py:61] CRITICAL test_api_18 (test_excel_api.TestAPI.test_api_18)
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 589, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\ddt.py", line 221, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mytest\UnittestDemo\testcase\test_excel_api.py", line 87, in test_api
    headers = ast.literal_eval(excel_data["headers"]) if excel_data["headers"] else eval(self.headers)
                                                                                    ^^^^^^^^^^^^^^^^^^
TypeError: eval() arg 1 must be a string, bytes or code object
[2024-10-21_14:04:57] - [run_x_test_runner_send_main.py:61] CRITICAL test_api_19 (test_excel_api.TestAPI.test_api_19)
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 589, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\ddt.py", line 221, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mytest\UnittestDemo\testcase\test_excel_api.py", line 87, in test_api
    headers = ast.literal_eval(excel_data["headers"]) if excel_data["headers"] else eval(self.headers)
                                                                                    ^^^^^^^^^^^^^^^^^^
TypeError: eval() arg 1 must be a string, bytes or code object
[2024-10-21_14:04:57] - [run_x_test_runner_send_main.py:61] CRITICAL test_api_20 (test_excel_api.TestAPI.test_api_20)
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 589, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\ddt.py", line 221, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mytest\UnittestDemo\testcase\test_excel_api.py", line 87, in test_api
    headers = ast.literal_eval(excel_data["headers"]) if excel_data["headers"] else eval(self.headers)
                                                                                    ^^^^^^^^^^^^^^^^^^
TypeError: eval() arg 1 must be a string, bytes or code object
[2024-10-21_14:04:57] - [run_x_test_runner_send_main.py:61] CRITICAL test_api_21 (test_excel_api.TestAPI.test_api_21)
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 589, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\ddt.py", line 221, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mytest\UnittestDemo\testcase\test_excel_api.py", line 87, in test_api
    headers = ast.literal_eval(excel_data["headers"]) if excel_data["headers"] else eval(self.headers)
                                                                                    ^^^^^^^^^^^^^^^^^^
TypeError: eval() arg 1 must be a string, bytes or code object
[2024-10-21_14:04:57] - [run_x_test_runner_send_main.py:61] CRITICAL test_api_22 (test_excel_api.TestAPI.test_api_22)
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 589, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\ddt.py", line 221, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mytest\UnittestDemo\testcase\test_excel_api.py", line 87, in test_api
    headers = ast.literal_eval(excel_data["headers"]) if excel_data["headers"] else eval(self.headers)
                                                                                    ^^^^^^^^^^^^^^^^^^
TypeError: eval() arg 1 must be a string, bytes or code object
[2024-10-21_14:04:57] - [run_x_test_runner_send_main.py:61] CRITICAL test_api_23 (test_excel_api.TestAPI.test_api_23)
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 589, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\ddt.py", line 221, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mytest\UnittestDemo\testcase\test_excel_api.py", line 87, in test_api
    headers = ast.literal_eval(excel_data["headers"]) if excel_data["headers"] else eval(self.headers)
                                                                                    ^^^^^^^^^^^^^^^^^^
TypeError: eval() arg 1 must be a string, bytes or code object
[2024-10-21_14:04:57] - [run_x_test_runner_send_main.py:61] CRITICAL test_api_24 (test_excel_api.TestAPI.test_api_24)
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 589, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\ddt.py", line 221, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mytest\UnittestDemo\testcase\test_excel_api.py", line 87, in test_api
    headers = ast.literal_eval(excel_data["headers"]) if excel_data["headers"] else eval(self.headers)
                                                                                    ^^^^^^^^^^^^^^^^^^
TypeError: eval() arg 1 must be a string, bytes or code object
[2024-10-21_14:04:57] - [run_x_test_runner_send_main.py:130] INFO 报告路径：D:\mytest\UnittestDemo\reports\result-20241021.html
[2024-10-21_14:06:57] - [run_x_test_runner_send_main.py:251] INFO main start...
[2024-10-21_14:07:17] - [run_x_test_runner_send_main.py:61] CRITICAL test_excel_api (unittest.loader._FailedTest.test_excel_api)
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 589, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\loader.py", line 33, in testFailure
    raise self._exception
ImportError: Failed to import test module: test_excel_api
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\loader.py", line 396, in _find_test_path
    module = self._get_module_from_name(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\loader.py", line 339, in _get_module_from_name
    __import__(name)
  File "D:\mytest\UnittestDemo\testcase\test_excel_api.py", line 16, in <module>
    from utils import verification_code_login
  File "D:\mytest\UnittestDemo\utils\verification_code_login.py", line 12, in <module>
    import muggle_ocr
  File "D:\mytest\UnittestDemo\muggle_ocr\__init__.py", line 5, in <module>
    from muggle_ocr.sdk import SDK
  File "D:\mytest\UnittestDemo\muggle_ocr\sdk.py", line 14, in <module>
    import tensorflow as tf
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\__init__.py", line 47, in <module>
    from tensorflow._api.v2 import __internal__
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\_api\v2\__internal__\__init__.py", line 11, in <module>
    from tensorflow._api.v2.__internal__ import distribute
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\_api\v2\__internal__\distribute\__init__.py", line 8, in <module>
    from tensorflow._api.v2.__internal__.distribute import combinations
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\_api\v2\__internal__\distribute\combinations\__init__.py", line 8, in <module>
    from tensorflow.python.distribute.combinations import env # line: 456
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\distribute\combinations.py", line 33, in <module>
    from tensorflow.python.distribute import collective_all_reduce_strategy
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\distribute\collective_all_reduce_strategy.py", line 25, in <module>
    from tensorflow.python.distribute import cross_device_ops as cross_device_ops_lib
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\distribute\cross_device_ops.py", line 28, in <module>
    from tensorflow.python.distribute import cross_device_utils
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\distribute\cross_device_utils.py", line 22, in <module>
    from tensorflow.python.distribute import values as value_lib
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\distribute\values.py", line 23, in <module>
    from tensorflow.python.distribute import distribute_lib
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\distribute\distribute_lib.py", line 205, in <module>
    from tensorflow.python.data.ops import dataset_ops
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\data\__init__.py", line 21, in <module>
    from tensorflow.python.data import experimental
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\data\experimental\__init__.py", line 98, in <module>
    from tensorflow.python.data.experimental import service
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\data\experimental\service\__init__.py", line 419, in <module>
    from tensorflow.python.data.experimental.ops.data_service_ops import distribute
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\data\experimental\ops\data_service_ops.py", line 23, in <module>
    from tensorflow.python.data.experimental.ops import compression_ops
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\data\experimental\ops\compression_ops.py", line 16, in <module>
    from tensorflow.python.data.util import structure
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\data\util\structure.py", line 32, in <module>
    from tensorflow.python.ops.ragged import ragged_tensor
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\ragged\__init__.py", line 28, in <module>
    from tensorflow.python.ops.ragged import ragged_tensor
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\ragged\ragged_tensor.py", line 3149, in <module>
    from tensorflow.python.ops.ragged import ragged_ops  # pylint: disable=unused-import, g-bad-import-order, g-import-not-at-top
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\ragged\ragged_ops.py", line 41, in <module>
    from tensorflow.python.ops.ragged import ragged_image_ops
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\ragged\ragged_image_ops.py", line 24, in <module>
    from tensorflow.python.ops import image_ops
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\image_ops.py", line 159, in <module>
    from tensorflow.python.ops.image_ops_impl import *
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\image_ops_impl.py", line 40, in <module>
    from tensorflow.python.ops import nn_impl
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\nn_impl.py", line 26, in <module>
    from tensorflow.python.ops import ctc_ops  # pylint: disable=unused-import
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\ctc_ops.py", line 32, in <module>
    from tensorflow.python.ops import custom_gradient
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\custom_gradient.py", line 17, in <module>
    from tensorflow.python.eager import backprop
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\eager\backprop.py", line 47, in <module>
    from tensorflow.python.ops.parallel_for import control_flow_ops as pfor_ops
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\parallel_for\control_flow_ops.py", line 37, in <module>
    from tensorflow.python.ops.parallel_for.pfor import PFor
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\parallel_for\pfor.py", line 71, in <module>
    from tensorflow.python.platform import flags
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\platform\flags.py", line 121, in <module>
    FLAGS = _FlagValuesWrapper(FLAGS)  # pylint: disable=used-before-assignment
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "_pydevd_bundle\\pydevd_pep_669_tracing_cython.pyx", line 504, in _pydevd_bundle.pydevd_pep_669_tracing_cython.PyRaiseCallback.__call__
  File "_pydevd_bundle\\pydevd_pep_669_tracing_cython.pyx", line 47, in _pydevd_bundle.pydevd_pep_669_tracing_cython.PEP669CallbackBase.frame
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\platform\flags.py", line 73, in __getattribute__
    return self.__dict__['__wrapped'].__getattribute__(name)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: '__wrapped'

[2024-10-21_14:07:19] - [run_x_test_runner_send_main.py:130] INFO 报告路径：D:\mytest\UnittestDemo\reports\result-20241021.html
[2024-10-21_14:08:36] - [run_x_test_runner_send_main.py:251] INFO main start...
[2024-10-21_14:08:39] - [verification_code_login.py:257] INFO 登录成功token：{'Content-Type': 'application/json;charset=utf-8', 'authorization': 'Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyRGVwdElkIjoxMDMsInVzZXJfaWQiOjEsInVzZXJfa2V5IjoiZTYwMjAzYWYtYjZiMy00NTBmLTg2ZTctMmM4YmQ5ZjkzNTMxIiwidXNlcm5hbWUiOiJhZG1pbiJ9.JgrIeDjl-Ar0oH16Xh8oD5JsaLxUje3umeGHARiUh0SPRw3zZhAZImgYEV7zxX18VZAn_RS2Og31w9K6lS73fg'}
[2024-10-21_14:08:39] - [run_x_test_runner_send_main.py:61] CRITICAL test_api_1 (test_excel_api.TestAPI.test_api_1)
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 589, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\ddt.py", line 221, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mytest\UnittestDemo\testcase\test_excel_api.py", line 87, in test_api
    headers = ast.literal_eval(excel_data["headers"]) if excel_data["headers"] else eval(self.headers)
                                                                                    ^^^^^^^^^^^^^^^^^^
TypeError: eval() arg 1 must be a string, bytes or code object
[2024-10-21_14:08:39] - [test_excel_api.py:170] INFO https://admin.liqicloud.com/prod-api/qiyelibrary/crm/project/reportable 响应数据：{"code":200,"msg":"Success","data":[]}
[2024-10-21_14:08:39] - [run_x_test_runner_send_main.py:130] INFO 报告路径：D:\mytest\UnittestDemo\reports\result-20241021.html
[2024-10-21_14:12:19] - [run_x_test_runner_send_main.py:251] INFO main start...
[2024-10-21_14:12:26] - [verification_code_login.py:257] INFO 登录成功token：{'Content-Type': 'application/json;charset=utf-8', 'authorization': 'Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyRGVwdElkIjoxMDMsInVzZXJfaWQiOjEsInVzZXJfa2V5IjoiMDU4NzM4MmUtNGU5Ni00NzUzLWFjNDAtYTNkZTI3NGZkNDRiIiwidXNlcm5hbWUiOiJhZG1pbiJ9.s3025JQFYAPo3GPG7dUeov9PxrkM7NOGtJ6BYtMGs8BOZmCpWDiiqgs0CZEh0jQb_S7arVKhZqi-uEsuB22zBA'}
[2024-10-21_14:12:26] - [run_x_test_runner_send_main.py:61] CRITICAL test_api_1 (test_excel_api.TestAPI.test_api_1)
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 589, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\ddt.py", line 221, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mytest\UnittestDemo\testcase\test_excel_api.py", line 88, in test_api
    headers = ast.literal_eval(excel_data["headers"]) if excel_data["headers"] else eval(self.headers)
                                                                                    ^^^^^^^^^^^^^^^^^^
TypeError: eval() arg 1 must be a string, bytes or code object
[2024-10-21_14:12:26] - [run_x_test_runner_send_main.py:61] CRITICAL test_api_2 (test_excel_api.TestAPI.test_api_2)
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 589, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\ddt.py", line 221, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mytest\UnittestDemo\testcase\test_excel_api.py", line 88, in test_api
    headers = ast.literal_eval(excel_data["headers"]) if excel_data["headers"] else eval(self.headers)
                                                                                    ^^^^^^^^^^^^^^^^^^
TypeError: eval() arg 1 must be a string, bytes or code object
[2024-10-21_14:12:26] - [run_x_test_runner_send_main.py:61] CRITICAL test_api_3 (test_excel_api.TestAPI.test_api_3)
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 589, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\ddt.py", line 221, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mytest\UnittestDemo\testcase\test_excel_api.py", line 88, in test_api
    headers = ast.literal_eval(excel_data["headers"]) if excel_data["headers"] else eval(self.headers)
                                                                                    ^^^^^^^^^^^^^^^^^^
TypeError: eval() arg 1 must be a string, bytes or code object
[2024-10-21_14:12:26] - [run_x_test_runner_send_main.py:130] INFO 报告路径：D:\mytest\UnittestDemo\reports\result-20241021.html
[2024-10-21_14:12:46] - [run_x_test_runner_send_main.py:251] INFO main start...
[2024-10-21_14:12:48] - [run_x_test_runner_send_main.py:61] CRITICAL test_excel_api (unittest.loader._FailedTest.test_excel_api)
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 589, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\loader.py", line 33, in testFailure
    raise self._exception
ImportError: Failed to import test module: test_excel_api
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\loader.py", line 396, in _find_test_path
    module = self._get_module_from_name(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\loader.py", line 339, in _get_module_from_name
    __import__(name)
  File "D:\mytest\UnittestDemo\testcase\test_excel_api.py", line 16, in <module>
    from utils import verification_code_login
  File "D:\mytest\UnittestDemo\utils\verification_code_login.py", line 12, in <module>
    import muggle_ocr
  File "D:\mytest\UnittestDemo\muggle_ocr\__init__.py", line 5, in <module>
    from muggle_ocr.sdk import SDK
  File "D:\mytest\UnittestDemo\muggle_ocr\sdk.py", line 14, in <module>
    import tensorflow as tf
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\__init__.py", line 47, in <module>
    from tensorflow._api.v2 import __internal__
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\_api\v2\__internal__\__init__.py", line 11, in <module>
    from tensorflow._api.v2.__internal__ import distribute
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\_api\v2\__internal__\distribute\__init__.py", line 8, in <module>
    from tensorflow._api.v2.__internal__.distribute import combinations
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\_api\v2\__internal__\distribute\combinations\__init__.py", line 8, in <module>
    from tensorflow.python.distribute.combinations import env # line: 456
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\distribute\combinations.py", line 33, in <module>
    from tensorflow.python.distribute import collective_all_reduce_strategy
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\distribute\collective_all_reduce_strategy.py", line 25, in <module>
    from tensorflow.python.distribute import cross_device_ops as cross_device_ops_lib
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\distribute\cross_device_ops.py", line 28, in <module>
    from tensorflow.python.distribute import cross_device_utils
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\distribute\cross_device_utils.py", line 22, in <module>
    from tensorflow.python.distribute import values as value_lib
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\distribute\values.py", line 23, in <module>
    from tensorflow.python.distribute import distribute_lib
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\distribute\distribute_lib.py", line 205, in <module>
    from tensorflow.python.data.ops import dataset_ops
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\data\__init__.py", line 21, in <module>
    from tensorflow.python.data import experimental
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\data\experimental\__init__.py", line 98, in <module>
    from tensorflow.python.data.experimental import service
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\data\experimental\service\__init__.py", line 419, in <module>
    from tensorflow.python.data.experimental.ops.data_service_ops import distribute
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\data\experimental\ops\data_service_ops.py", line 23, in <module>
    from tensorflow.python.data.experimental.ops import compression_ops
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\data\experimental\ops\compression_ops.py", line 16, in <module>
    from tensorflow.python.data.util import structure
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\data\util\structure.py", line 32, in <module>
    from tensorflow.python.ops.ragged import ragged_tensor
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\ragged\__init__.py", line 28, in <module>
    from tensorflow.python.ops.ragged import ragged_tensor
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\ragged\ragged_tensor.py", line 3149, in <module>
    from tensorflow.python.ops.ragged import ragged_ops  # pylint: disable=unused-import, g-bad-import-order, g-import-not-at-top
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\ragged\ragged_ops.py", line 41, in <module>
    from tensorflow.python.ops.ragged import ragged_image_ops
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\ragged\ragged_image_ops.py", line 24, in <module>
    from tensorflow.python.ops import image_ops
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\image_ops.py", line 159, in <module>
    from tensorflow.python.ops.image_ops_impl import *
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\image_ops_impl.py", line 40, in <module>
    from tensorflow.python.ops import nn_impl
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\nn_impl.py", line 26, in <module>
    from tensorflow.python.ops import ctc_ops  # pylint: disable=unused-import
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\ctc_ops.py", line 32, in <module>
    from tensorflow.python.ops import custom_gradient
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\custom_gradient.py", line 17, in <module>
    from tensorflow.python.eager import backprop
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\eager\backprop.py", line 47, in <module>
    from tensorflow.python.ops.parallel_for import control_flow_ops as pfor_ops
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\parallel_for\control_flow_ops.py", line 37, in <module>
    from tensorflow.python.ops.parallel_for.pfor import PFor
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\parallel_for\pfor.py", line 71, in <module>
    from tensorflow.python.platform import flags
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\platform\flags.py", line 121, in <module>
    FLAGS = _FlagValuesWrapper(FLAGS)  # pylint: disable=used-before-assignment
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "_pydevd_bundle\\pydevd_pep_669_tracing_cython.pyx", line 504, in _pydevd_bundle.pydevd_pep_669_tracing_cython.PyRaiseCallback.__call__
  File "_pydevd_bundle\\pydevd_pep_669_tracing_cython.pyx", line 47, in _pydevd_bundle.pydevd_pep_669_tracing_cython.PEP669CallbackBase.frame
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\platform\flags.py", line 73, in __getattribute__
    return self.__dict__['__wrapped'].__getattribute__(name)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: '__wrapped'

[2024-10-21_14:12:48] - [run_x_test_runner_send_main.py:130] INFO 报告路径：D:\mytest\UnittestDemo\reports\result-20241021.html
[2024-10-21_14:14:18] - [run_x_test_runner_send_main.py:251] INFO main start...
[2024-10-21_14:14:21] - [verification_code_login.py:257] INFO 登录成功token：{'Content-Type': 'application/json;charset=utf-8', 'authorization': 'Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyRGVwdElkIjoxMDMsInVzZXJfaWQiOjEsInVzZXJfa2V5IjoiMzdlOGNhZWItMTk4Ny00NzlkLWFmMTUtNzhhM2FlMGM0MjYxIiwidXNlcm5hbWUiOiJhZG1pbiJ9.4z9yE-7Qze6Kb4FnXbxuQYRrbxQLiGESDjeOmG8DFUHOFbSCwweta6nuaFRw75ZGoc4769e_mrOeguYuQqmQ0g'}
[2024-10-21_14:14:21] - [test_excel_api.py:88] WARNING {'Content-Type': 'application/json;charset=utf-8', 'authorization': 'Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyRGVwdElkIjoxMDMsInVzZXJfaWQiOjEsInVzZXJfa2V5IjoiMzdlOGNhZWItMTk4Ny00NzlkLWFmMTUtNzhhM2FlMGM0MjYxIiwidXNlcm5hbWUiOiJhZG1pbiJ9.4z9yE-7Qze6Kb4FnXbxuQYRrbxQLiGESDjeOmG8DFUHOFbSCwweta6nuaFRw75ZGoc4769e_mrOeguYuQqmQ0g'}
[2024-10-21_14:14:21] - [run_x_test_runner_send_main.py:61] CRITICAL test_api_1 (test_excel_api.TestAPI.test_api_1)
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 589, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\ddt.py", line 221, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mytest\UnittestDemo\testcase\test_excel_api.py", line 90, in test_api
    headers = ast.literal_eval(excel_data["headers"]) if excel_data["headers"] else eval(self.headers)
                                                                                    ^^^^^^^^^^^^^^^^^^
TypeError: eval() arg 1 must be a string, bytes or code object
[2024-10-21_14:14:21] - [test_excel_api.py:88] WARNING {'Content-Type': 'application/json;charset=utf-8', 'authorization': 'Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyRGVwdElkIjoxMDMsInVzZXJfaWQiOjEsInVzZXJfa2V5IjoiMzdlOGNhZWItMTk4Ny00NzlkLWFmMTUtNzhhM2FlMGM0MjYxIiwidXNlcm5hbWUiOiJhZG1pbiJ9.4z9yE-7Qze6Kb4FnXbxuQYRrbxQLiGESDjeOmG8DFUHOFbSCwweta6nuaFRw75ZGoc4769e_mrOeguYuQqmQ0g'}
[2024-10-21_14:14:21] - [run_x_test_runner_send_main.py:61] CRITICAL test_api_2 (test_excel_api.TestAPI.test_api_2)
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 589, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\ddt.py", line 221, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mytest\UnittestDemo\testcase\test_excel_api.py", line 90, in test_api
    headers = ast.literal_eval(excel_data["headers"]) if excel_data["headers"] else eval(self.headers)
                                                                                    ^^^^^^^^^^^^^^^^^^
TypeError: eval() arg 1 must be a string, bytes or code object
[2024-10-21_14:14:21] - [test_excel_api.py:88] WARNING {'Content-Type': 'application/json;charset=utf-8', 'authorization': 'Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyRGVwdElkIjoxMDMsInVzZXJfaWQiOjEsInVzZXJfa2V5IjoiMzdlOGNhZWItMTk4Ny00NzlkLWFmMTUtNzhhM2FlMGM0MjYxIiwidXNlcm5hbWUiOiJhZG1pbiJ9.4z9yE-7Qze6Kb4FnXbxuQYRrbxQLiGESDjeOmG8DFUHOFbSCwweta6nuaFRw75ZGoc4769e_mrOeguYuQqmQ0g'}
[2024-10-21_14:14:21] - [run_x_test_runner_send_main.py:61] CRITICAL test_api_3 (test_excel_api.TestAPI.test_api_3)
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 589, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\ddt.py", line 221, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mytest\UnittestDemo\testcase\test_excel_api.py", line 90, in test_api
    headers = ast.literal_eval(excel_data["headers"]) if excel_data["headers"] else eval(self.headers)
                                                                                    ^^^^^^^^^^^^^^^^^^
TypeError: eval() arg 1 must be a string, bytes or code object
[2024-10-21_14:14:21] - [run_x_test_runner_send_main.py:130] INFO 报告路径：D:\mytest\UnittestDemo\reports\result-20241021.html
[2024-10-21_14:15:55] - [run_x_test_runner_send_main.py:251] INFO main start...
[2024-10-21_14:16:00] - [verification_code_login.py:257] INFO 登录成功token：{'Content-Type': 'application/json;charset=utf-8', 'authorization': 'Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyRGVwdElkIjoxMDMsInVzZXJfaWQiOjEsInVzZXJfa2V5IjoiMzQyZTc0MzMtOGQ4My00MDBjLWJjMTQtZmYwMmY1ZDA2NGY2IiwidXNlcm5hbWUiOiJhZG1pbiJ9.XHQvOjf_rm1-uGIRIT8zu5Z7JshBU909HP5OJS_7AWfDqLMsCcNv6-ONrPpL-1iMKysORplXm8yyWNctZZigXg'}
[2024-10-21_14:16:00] - [test_excel_api.py:88] WARNING {'Content-Type': 'application/json;charset=utf-8', 'authorization': 'Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyRGVwdElkIjoxMDMsInVzZXJfaWQiOjEsInVzZXJfa2V5IjoiMzQyZTc0MzMtOGQ4My00MDBjLWJjMTQtZmYwMmY1ZDA2NGY2IiwidXNlcm5hbWUiOiJhZG1pbiJ9.XHQvOjf_rm1-uGIRIT8zu5Z7JshBU909HP5OJS_7AWfDqLMsCcNv6-ONrPpL-1iMKysORplXm8yyWNctZZigXg'}
[2024-10-21_14:16:00] - [test_excel_api.py:274] INFO 提取变量：1848244063521959937
[2024-10-21_14:16:00] - [test_excel_api.py:173] INFO /test-api/system/applet/feedback/backend/list 响应数据：{"code":200,"msg":"Success","data":{"page":1,"size":10,"total":2,"list":[{"id":"1848244063521959937","appUserId":"1840678944340381697","appUserName":"用户188****7806","appUserSubmitName":"用户188****7806","appUserPhone":"18813537806","submitIssueType":1,"submitIssueDescription":"测试反馈内容","submitIssueTime":"2024-10-21 14:04:58","uploadImageUrl":"https://lqc-public-oss-pre.oss-cn-shenzhen.aliyuncs.com/test/lqc-app/c5c931dadc424b71a60326da53828fb6.jpg","replyStatus":0,"replyText":null,"replyTime":null,"replyerName":"启程智远"},{"id":"1847543017367629825","appUserId":"1840678944340381697","appUserName":"用户188****7806","appUserSubmitName":"用户188****7806","appUserPhone":"18813537806","submitIssueType":1,"submitIssueDescription":"你看看吧，","submitIssueTime":"2024-10-19 15:39:15","uploadImageUrl":"https://lqc-public-oss-pre.oss-cn-shenzhen.aliyuncs.com/test/lqc-app/9efcddd7ff1a4f73993ff485bd423fb7.jpg","replyStatus":0,"replyText":null,"replyTime":null,"replyerName":"启程智远"}]}}
[2024-10-21_14:16:00] - [test_excel_api.py:88] WARNING {'Content-Type': 'application/json;charset=utf-8', 'authorization': 'Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyRGVwdElkIjoxMDMsInVzZXJfaWQiOjEsInVzZXJfa2V5IjoiMzQyZTc0MzMtOGQ4My00MDBjLWJjMTQtZmYwMmY1ZDA2NGY2IiwidXNlcm5hbWUiOiJhZG1pbiJ9.XHQvOjf_rm1-uGIRIT8zu5Z7JshBU909HP5OJS_7AWfDqLMsCcNv6-ONrPpL-1iMKysORplXm8yyWNctZZigXg'}
[2024-10-21_14:16:00] - [test_excel_api.py:274] INFO 提取变量：10086168
[2024-10-21_14:16:00] - [test_excel_api.py:173] INFO /test-api/policylibrary/policy/crawlData/select 响应数据：{"code":200,"msg":"Success","data":{"page":1,"size":10,"total":5,"list":[{"crawlDataId":10086168,"title":"湖南省人民政府 国家知识产权局关于印发《湖南省人民政府 国家知识产权局共建“三高四新”知识产权强省实施方案》的通知","originText":null,"crawlDataMd5":"bb6d3ec9cf44e795940f9f5fb44235b4","url":"https://www.hunan.gov.cn/hnszf/xxgk/wjk/szfwj/202208/t20220805_27576139.html","dumpBusinessId":"1847173170336882690","crawlFileList":null,"dumpStatus":0,"dumpStatusName":"未转存","dumpType":3,"dumpTypeName":"政策资讯","officialPublishTime":"2022-07-25 00:00:00","crawlTime":"2024-10-18 14:49:53","rank":2,"rankName":"省级","provinceCode":"430000","provinceName":"湖南省","cityCode":null,"cityName":null,"areaCode":null,"areaName":null,"deptId":22861,"deptName":"湖南省水利厅","phone":null,"address":null,"categoryVOList":null,"projectBaseInfoVO":null,"checkTime":"2024-10-19 13:48:11","checkerId":1,"checkerName":"启程智远","markerName":"系统","markerId":45,"markStatus":6,"markTime":"2024-10-18 15:09:37","recognizeType":2,"recognizeTypeVal":"政策资讯"},{"crawlDataId":59266,"title":"青岛市人力资源和社会保障局关于技术技能提升补贴申领发放情况的说明","originText":null,"crawlDataMd5":"6b18caaed33ab83dd67b8536e8bce002","url":"https://hrss.qingdao.gov.cn/zxzx_47/tzgg_47/202206/t20220617_6176065.shtml","dumpBusinessId":null,"crawlFileList":null,"dumpStatus":0,"dumpStatusName":"未转存","dumpType":null,"dumpTypeName":null,"officialPublishTime":"2021-01-25 00:00:00","crawlTime":"2024-04-28 12:00:00","rank":1,"rankName":"国家级","provinceCode":null,"provinceName":null,"cityCode":null,"cityName":null,"areaCode":null,"areaName":null,"deptId":null,"deptName":null,"phone":null,"address":null,"categoryVOList":null,"projectBaseInfoVO":null,"checkTime":null,"checkerId":null,"checkerName":null,"markerName":"启程智远","markerId":1,"markStatus":6,"markTime":"2024-07-26 17:05:30","recognizeType":6,"recognizeTypeVal":null},{"crawlDataId":59207,"title":"关于实施援企稳岗政策有关情况的通知","originText":null,"crawlDataMd5":"3c9c77d00ca859e2e5153aadb4d6991f","url":"https://hrss.qingdao.gov.cn/zxzx_47/tzgg_47/202206/t20220617_6174043.shtml","dumpBusinessId":null,"crawlFileList":null,"dumpStatus":0,"dumpStatusName":"未转存","dumpType":null,"dumpTypeName":null,"officialPublishTime":"2020-06-30 00:00:00","crawlTime":"2024-04-28 12:00:00","rank":1,"rankName":"国家级","provinceCode":null,"provinceName":null,"cityCode":null,"cityName":null,"areaCode":null,"areaName":null,"deptId":null,"deptName":null,"phone":null,"address":null,"categoryVOList":null,"projectBaseInfoVO":null,"checkTime":null,"checkerId":null,"checkerName":null,"markerName":"启程智远","markerId":1,"markStatus":6,"markTime":"2024-09-24 16:05:27","recognizeType":6,"recognizeTypeVal":null},{"crawlDataId":59203,"title":"关于举行湛山创客工厂第十三批入驻企业答辩评审会的通知","originText":null,"crawlDataMd5":"aa55470cdae56972945af7ea69d99a77","url":"https://hrss.qingdao.gov.cn/zxzx_47/tzgg_47/202206/t20220617_6174033.shtml","dumpBusinessId":null,"crawlFileList":null,"dumpStatus":0,"dumpStatusName":"未转存","dumpType":null,"dumpTypeName":null,"officialPublishTime":"2020-07-24 00:00:00","crawlTime":"2024-04-28 12:00:00","rank":1,"rankName":"国家级","provinceCode":null,"provinceName":null,"cityCode":null,"cityName":null,"areaCode":null,"areaName":null,"deptId":null,"deptName":null,"phone":null,"address":null,"categoryVOList":null,"projectBaseInfoVO":null,"checkTime":null,"checkerId":null,"checkerName":null,"markerName":"启程智远","markerId":1,"markStatus":6,"markTime":"2024-09-24 16:14:01","recognizeType":6,"recognizeTypeVal":null},{"crawlDataId":59178,"title":"关于停止水平评价类技能人员职业资格证书发放工作的通知","originText":null,"crawlDataMd5":"78921fb1a3ff24d663f22383c157756e","url":"https://hrss.qingdao.gov.cn/zxzx_47/tzgg_47/202206/t20220613_6137909.shtml","dumpBusinessId":null,"crawlFileList":null,"dumpStatus":0,"dumpStatusName":"未转存","dumpType":null,"dumpTypeName":null,"officialPublishTime":"2022-03-21 00:00:00","crawlTime":"2024-04-28 12:00:00","rank":1,"rankName":"国家级","provinceCode":null,"provinceName":null,"cityCode":null,"cityName":null,"areaCode":null,"areaName":null,"deptId":null,"deptName":null,"phone":null,"address":null,"categoryVOList":null,"projectBaseInfoVO":null,"checkTime":null,"checkerId":null,"checkerName":null,"markerName":"启程智远","markerId":1,"markStatus":6,"markTime":"2024-09-25 16:30:37","recognizeType":6,"recognizeTypeVal":null}]}}
[2024-10-21_14:16:00] - [test_excel_api.py:88] WARNING {'Content-Type': 'application/json;charset=utf-8', 'authorization': 'Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyRGVwdElkIjoxMDMsInVzZXJfaWQiOjEsInVzZXJfa2V5IjoiMzQyZTc0MzMtOGQ4My00MDBjLWJjMTQtZmYwMmY1ZDA2NGY2IiwidXNlcm5hbWUiOiJhZG1pbiJ9.XHQvOjf_rm1-uGIRIT8zu5Z7JshBU909HP5OJS_7AWfDqLMsCcNv6-ONrPpL-1iMKysORplXm8yyWNctZZigXg'}
[2024-10-21_14:16:00] - [test_excel_api.py:253] INFO 变量替换：variable2 => 10086168
[2024-10-21_14:16:00] - [test_excel_api.py:173] INFO /test-api/policylibrary/policy/crawlData/back/${variable2} 响应数据：{"code":200,"msg":null,"data":null}
[2024-10-21_14:16:01] - [run_x_test_runner_send_main.py:130] INFO 报告路径：D:\mytest\UnittestDemo\reports\result-20241021.html
[2024-10-21_14:23:52] - [run_x_test_runner_send_main.py:251] INFO main start...
[2024-10-21_14:23:54] - [verification_code_login.py:214] INFO {'code': 500, 'msg': '验证码不能为空'}
[2024-10-21_14:23:55] - [verification_code_login.py:214] INFO {'code': 500, 'msg': '验证码不能为空'}
[2024-10-21_14:23:55] - [verification_code_login.py:214] INFO {'code': 500, 'msg': '验证码错误'}
[2024-10-21_14:23:56] - [verification_code_login.py:214] INFO {'code': 500, 'msg': '验证码不能为空'}
[2024-10-21_14:23:56] - [verification_code_login.py:257] INFO 登录成功 {'Content-Type': 'application/json;charset=utf-8', 'authorization': 'Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyRGVwdElkIjoxMDMsInVzZXJfaWQiOjEsInVzZXJfa2V5IjoiYzk3NGVhMTItYmQ2OC00ZTM3LThmMGItYzdjYmYwNDA2ZTlmIiwidXNlcm5hbWUiOiJhZG1pbiJ9.zQ_3aabKoGsrJBdtNjYhUG_sobMq4WVj-0Nsjj8acf2XZoDrQV8BE1jfv7P3D8sFdgmeimfauKxonTC9xynupw'}
[2024-10-21_14:23:56] - [test_excel_api.py:275] INFO 提取变量：1848244063521959937
[2024-10-21_14:23:56] - [test_excel_api.py:174] INFO /test-api/system/applet/feedback/backend/list 响应数据：{"code":200,"msg":"Success","data":{"page":1,"size":10,"total":2,"list":[{"id":"1848244063521959937","appUserId":"1840678944340381697","appUserName":"用户188****7806","appUserSubmitName":"用户188****7806","appUserPhone":"18813537806","submitIssueType":1,"submitIssueDescription":"测试反馈内容","submitIssueTime":"2024-10-21 14:04:58","uploadImageUrl":"https://lqc-public-oss-pre.oss-cn-shenzhen.aliyuncs.com/test/lqc-app/c5c931dadc424b71a60326da53828fb6.jpg","replyStatus":0,"replyText":null,"replyTime":null,"replyerName":"启程智远"},{"id":"1847543017367629825","appUserId":"1840678944340381697","appUserName":"用户188****7806","appUserSubmitName":"用户188****7806","appUserPhone":"18813537806","submitIssueType":1,"submitIssueDescription":"你看看吧，","submitIssueTime":"2024-10-19 15:39:15","uploadImageUrl":"https://lqc-public-oss-pre.oss-cn-shenzhen.aliyuncs.com/test/lqc-app/9efcddd7ff1a4f73993ff485bd423fb7.jpg","replyStatus":0,"replyText":null,"replyTime":null,"replyerName":"启程智远"}]}}
[2024-10-21_14:23:57] - [test_excel_api.py:275] INFO 提取变量：59266
[2024-10-21_14:23:57] - [test_excel_api.py:174] INFO /test-api/policylibrary/policy/crawlData/select 响应数据：{"code":200,"msg":"Success","data":{"page":1,"size":10,"total":4,"list":[{"crawlDataId":59266,"title":"青岛市人力资源和社会保障局关于技术技能提升补贴申领发放情况的说明","originText":null,"crawlDataMd5":"6b18caaed33ab83dd67b8536e8bce002","url":"https://hrss.qingdao.gov.cn/zxzx_47/tzgg_47/202206/t20220617_6176065.shtml","dumpBusinessId":null,"crawlFileList":null,"dumpStatus":0,"dumpStatusName":"未转存","dumpType":null,"dumpTypeName":null,"officialPublishTime":"2021-01-25 00:00:00","crawlTime":"2024-04-28 12:00:00","rank":1,"rankName":"国家级","provinceCode":null,"provinceName":null,"cityCode":null,"cityName":null,"areaCode":null,"areaName":null,"deptId":null,"deptName":null,"phone":null,"address":null,"categoryVOList":null,"projectBaseInfoVO":null,"checkTime":null,"checkerId":null,"checkerName":null,"markerName":"启程智远","markerId":1,"markStatus":6,"markTime":"2024-07-26 17:05:30","recognizeType":6,"recognizeTypeVal":null},{"crawlDataId":59207,"title":"关于实施援企稳岗政策有关情况的通知","originText":null,"crawlDataMd5":"3c9c77d00ca859e2e5153aadb4d6991f","url":"https://hrss.qingdao.gov.cn/zxzx_47/tzgg_47/202206/t20220617_6174043.shtml","dumpBusinessId":null,"crawlFileList":null,"dumpStatus":0,"dumpStatusName":"未转存","dumpType":null,"dumpTypeName":null,"officialPublishTime":"2020-06-30 00:00:00","crawlTime":"2024-04-28 12:00:00","rank":1,"rankName":"国家级","provinceCode":null,"provinceName":null,"cityCode":null,"cityName":null,"areaCode":null,"areaName":null,"deptId":null,"deptName":null,"phone":null,"address":null,"categoryVOList":null,"projectBaseInfoVO":null,"checkTime":null,"checkerId":null,"checkerName":null,"markerName":"启程智远","markerId":1,"markStatus":6,"markTime":"2024-09-24 16:05:27","recognizeType":6,"recognizeTypeVal":null},{"crawlDataId":59203,"title":"关于举行湛山创客工厂第十三批入驻企业答辩评审会的通知","originText":null,"crawlDataMd5":"aa55470cdae56972945af7ea69d99a77","url":"https://hrss.qingdao.gov.cn/zxzx_47/tzgg_47/202206/t20220617_6174033.shtml","dumpBusinessId":null,"crawlFileList":null,"dumpStatus":0,"dumpStatusName":"未转存","dumpType":null,"dumpTypeName":null,"officialPublishTime":"2020-07-24 00:00:00","crawlTime":"2024-04-28 12:00:00","rank":1,"rankName":"国家级","provinceCode":null,"provinceName":null,"cityCode":null,"cityName":null,"areaCode":null,"areaName":null,"deptId":null,"deptName":null,"phone":null,"address":null,"categoryVOList":null,"projectBaseInfoVO":null,"checkTime":null,"checkerId":null,"checkerName":null,"markerName":"启程智远","markerId":1,"markStatus":6,"markTime":"2024-09-24 16:14:01","recognizeType":6,"recognizeTypeVal":null},{"crawlDataId":59178,"title":"关于停止水平评价类技能人员职业资格证书发放工作的通知","originText":null,"crawlDataMd5":"78921fb1a3ff24d663f22383c157756e","url":"https://hrss.qingdao.gov.cn/zxzx_47/tzgg_47/202206/t20220613_6137909.shtml","dumpBusinessId":null,"crawlFileList":null,"dumpStatus":0,"dumpStatusName":"未转存","dumpType":null,"dumpTypeName":null,"officialPublishTime":"2022-03-21 00:00:00","crawlTime":"2024-04-28 12:00:00","rank":1,"rankName":"国家级","provinceCode":null,"provinceName":null,"cityCode":null,"cityName":null,"areaCode":null,"areaName":null,"deptId":null,"deptName":null,"phone":null,"address":null,"categoryVOList":null,"projectBaseInfoVO":null,"checkTime":null,"checkerId":null,"checkerName":null,"markerName":"启程智远","markerId":1,"markStatus":6,"markTime":"2024-09-25 16:30:37","recognizeType":6,"recognizeTypeVal":null}]}}
[2024-10-21_14:23:57] - [test_excel_api.py:254] INFO 变量替换：variable2 => 59266
[2024-10-21_14:23:57] - [test_excel_api.py:174] INFO /test-api/policylibrary/policy/crawlData/back/${variable2} 响应数据：{"code":200,"msg":null,"data":null}
[2024-10-21_14:23:57] - [run_x_test_runner_send_main.py:130] INFO 报告路径：D:\mytest\UnittestDemo\reports\result-20241021.html
[2024-10-21_14:41:46] - [run_x_test_runner_send_main.py:251] INFO main start...
[2024-10-21_14:41:48] - [verification_code_login.py:218] INFO {'code': 500, 'msg': '验证码不能为空'}
[2024-10-21_14:41:49] - [verification_code_login.py:218] INFO {'code': 500, 'msg': '验证码不能为空'}
[2024-10-21_14:41:49] - [verification_code_login.py:218] INFO {'code': 500, 'msg': '验证码不能为空'}
[2024-10-21_14:41:50] - [verification_code_login.py:218] INFO {'code': 500, 'msg': '验证码不能为空'}
[2024-10-21_14:41:50] - [verification_code_login.py:218] INFO {'code': 500, 'msg': '验证码不能为空'}
[2024-10-21_14:41:51] - [verification_code_login.py:218] INFO {'code': 500, 'msg': '验证码不能为空'}
[2024-10-21_14:41:55] - [verification_code_login.py:264] ERROR 登录失败！
[2024-10-21_14:41:55] - [test_excel_api.py:174] INFO /test-api/system/applet/feedback/backend/list 响应数据：{"code":401,"msg":"登录状态已过期"}
[2024-10-21_14:41:55] - [test_excel_api.py:190] WARNING 请求参数：{"pageNo":1,"pageSize":10,"appUserName":"用户188****7806","replyStatus":0}
[2024-10-21_14:41:55] - [run_x_test_runner_send_main.py:56] ERROR test_api_1 (test_excel_api.TestAPI.test_api_1)
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 589, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\ddt.py", line 221, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mytest\UnittestDemo\testcase\test_excel_api.py", line 191, in test_api
    raise e
  File "D:\mytest\UnittestDemo\testcase\test_excel_api.py", line 186, in test_api
    self.assertIn(msg, response.content.decode("utf-8"), f"{case_id} {title} {url}")
AssertionError: '测试反馈内容' not found in '{"code":401,"msg":"登录状态已过期"}' : lqc_17 查询根据用户名查询没有回复的记录 /test-api/system/applet/feedback/backend/list
[2024-10-21_14:41:55] - [test_excel_api.py:174] INFO /test-api/policylibrary/policy/crawlData/select 响应数据：{"code":401,"msg":"登录状态已过期"}
[2024-10-21_14:41:55] - [test_excel_api.py:190] WARNING 请求参数：{"pageSize":10,"pageNo":1,"markStatus":6}
[2024-10-21_14:41:55] - [run_x_test_runner_send_main.py:56] ERROR test_api_2 (test_excel_api.TestAPI.test_api_2)
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 589, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\ddt.py", line 221, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mytest\UnittestDemo\testcase\test_excel_api.py", line 191, in test_api
    raise e
  File "D:\mytest\UnittestDemo\testcase\test_excel_api.py", line 186, in test_api
    self.assertIn(msg, response.content.decode("utf-8"), f"{case_id} {title} {url}")
AssertionError: '"code":200' not found in '{"code":401,"msg":"登录状态已过期"}' : lqc_24 查询无效数据 /test-api/policylibrary/policy/crawlData/select
[2024-10-21_14:41:55] - [test_excel_api.py:254] INFO 变量替换：variable2 => None
[2024-10-21_14:41:55] - [test_excel_api.py:174] INFO /test-api/policylibrary/policy/crawlData/back/${variable2} 响应数据：{"code":401,"msg":"登录状态已过期"}
[2024-10-21_14:41:55] - [test_excel_api.py:190] WARNING 请求参数：None
[2024-10-21_14:41:55] - [run_x_test_runner_send_main.py:56] ERROR test_api_3 (test_excel_api.TestAPI.test_api_3)
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 589, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\ddt.py", line 221, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mytest\UnittestDemo\testcase\test_excel_api.py", line 191, in test_api
    raise e
  File "D:\mytest\UnittestDemo\testcase\test_excel_api.py", line 186, in test_api
    self.assertIn(msg, response.content.decode("utf-8"), f"{case_id} {title} {url}")
AssertionError: '"code":200' not found in '{"code":401,"msg":"登录状态已过期"}' : lqc_25 恢复用户释放成无效状态的数据 /test-api/policylibrary/policy/crawlData/back/${variable2}
[2024-10-21_14:41:55] - [run_x_test_runner_send_main.py:130] INFO 报告路径：D:\mytest\UnittestDemo\reports\result-20241021.html
[2024-10-21_14:42:17] - [run_x_test_runner_send_main.py:251] INFO main start...
[2024-10-21_14:42:19] - [verification_code_login.py:218] INFO {'code': 500, 'msg': '验证码不能为空'}
[2024-10-21_14:42:19] - [verification_code_login.py:218] INFO {'code': 500, 'msg': '验证码不能为空'}
[2024-10-21_14:42:20] - [verification_code_login.py:261] INFO 登录成功 {'Content-Type': 'application/json;charset=utf-8', 'authorization': 'Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyRGVwdElkIjoxMDMsInVzZXJfaWQiOjEsInVzZXJfa2V5IjoiMDY5MmI4MjMtYjQ0Yi00NTExLThiODQtNmI1MmNjYzRkMGJjIiwidXNlcm5hbWUiOiJhZG1pbiJ9.ZZO0wwlyJSXyeoAxDcWUgui1hfoefL-9acQ3bN-9QgmLy-8U1o-_gSl-6m1PFuWHvUP7vHiSRZi6S0lJ06UFMw'}
[2024-10-21_14:42:20] - [test_excel_api.py:275] INFO 提取变量：0 => 1848244063521959937
[2024-10-21_14:42:20] - [test_excel_api.py:174] INFO /test-api/system/applet/feedback/backend/list 响应数据：{"code":200,"msg":"Success","data":{"page":1,"size":10,"total":2,"list":[{"id":"1848244063521959937","appUserId":"1840678944340381697","appUserName":"用户188****7806","appUserSubmitName":"用户188****7806","appUserPhone":"18813537806","submitIssueType":1,"submitIssueDescription":"测试反馈内容","submitIssueTime":"2024-10-21 14:04:58","uploadImageUrl":"https://lqc-public-oss-pre.oss-cn-shenzhen.aliyuncs.com/test/lqc-app/c5c931dadc424b71a60326da53828fb6.jpg","replyStatus":0,"replyText":null,"replyTime":null,"replyerName":"启程智远"},{"id":"1847543017367629825","appUserId":"1840678944340381697","appUserName":"用户188****7806","appUserSubmitName":"用户188****7806","appUserPhone":"18813537806","submitIssueType":1,"submitIssueDescription":"你看看吧，","submitIssueTime":"2024-10-19 15:39:15","uploadImageUrl":"https://lqc-public-oss-pre.oss-cn-shenzhen.aliyuncs.com/test/lqc-app/9efcddd7ff1a4f73993ff485bd423fb7.jpg","replyStatus":0,"replyText":null,"replyTime":null,"replyerName":"启程智远"}]}}
[2024-10-21_14:42:21] - [test_excel_api.py:275] INFO 提取变量：1 => 59207
[2024-10-21_14:42:21] - [test_excel_api.py:174] INFO /test-api/policylibrary/policy/crawlData/select 响应数据：{"code":200,"msg":"Success","data":{"page":1,"size":10,"total":3,"list":[{"crawlDataId":59207,"title":"关于实施援企稳岗政策有关情况的通知","originText":null,"crawlDataMd5":"3c9c77d00ca859e2e5153aadb4d6991f","url":"https://hrss.qingdao.gov.cn/zxzx_47/tzgg_47/202206/t20220617_6174043.shtml","dumpBusinessId":null,"crawlFileList":null,"dumpStatus":0,"dumpStatusName":"未转存","dumpType":null,"dumpTypeName":null,"officialPublishTime":"2020-06-30 00:00:00","crawlTime":"2024-04-28 12:00:00","rank":1,"rankName":"国家级","provinceCode":null,"provinceName":null,"cityCode":null,"cityName":null,"areaCode":null,"areaName":null,"deptId":null,"deptName":null,"phone":null,"address":null,"categoryVOList":null,"projectBaseInfoVO":null,"checkTime":null,"checkerId":null,"checkerName":null,"markerName":"启程智远","markerId":1,"markStatus":6,"markTime":"2024-09-24 16:05:27","recognizeType":6,"recognizeTypeVal":null},{"crawlDataId":59203,"title":"关于举行湛山创客工厂第十三批入驻企业答辩评审会的通知","originText":null,"crawlDataMd5":"aa55470cdae56972945af7ea69d99a77","url":"https://hrss.qingdao.gov.cn/zxzx_47/tzgg_47/202206/t20220617_6174033.shtml","dumpBusinessId":null,"crawlFileList":null,"dumpStatus":0,"dumpStatusName":"未转存","dumpType":null,"dumpTypeName":null,"officialPublishTime":"2020-07-24 00:00:00","crawlTime":"2024-04-28 12:00:00","rank":1,"rankName":"国家级","provinceCode":null,"provinceName":null,"cityCode":null,"cityName":null,"areaCode":null,"areaName":null,"deptId":null,"deptName":null,"phone":null,"address":null,"categoryVOList":null,"projectBaseInfoVO":null,"checkTime":null,"checkerId":null,"checkerName":null,"markerName":"启程智远","markerId":1,"markStatus":6,"markTime":"2024-09-24 16:14:01","recognizeType":6,"recognizeTypeVal":null},{"crawlDataId":59178,"title":"关于停止水平评价类技能人员职业资格证书发放工作的通知","originText":null,"crawlDataMd5":"78921fb1a3ff24d663f22383c157756e","url":"https://hrss.qingdao.gov.cn/zxzx_47/tzgg_47/202206/t20220613_6137909.shtml","dumpBusinessId":null,"crawlFileList":null,"dumpStatus":0,"dumpStatusName":"未转存","dumpType":null,"dumpTypeName":null,"officialPublishTime":"2022-03-21 00:00:00","crawlTime":"2024-04-28 12:00:00","rank":1,"rankName":"国家级","provinceCode":null,"provinceName":null,"cityCode":null,"cityName":null,"areaCode":null,"areaName":null,"deptId":null,"deptName":null,"phone":null,"address":null,"categoryVOList":null,"projectBaseInfoVO":null,"checkTime":null,"checkerId":null,"checkerName":null,"markerName":"启程智远","markerId":1,"markStatus":6,"markTime":"2024-09-25 16:30:37","recognizeType":6,"recognizeTypeVal":null}]}}
[2024-10-21_14:42:21] - [test_excel_api.py:254] INFO 变量替换：variable2 => 59207
[2024-10-21_14:42:21] - [test_excel_api.py:174] INFO /test-api/policylibrary/policy/crawlData/back/${variable2} 响应数据：{"code":200,"msg":null,"data":null}
[2024-10-21_14:42:21] - [run_x_test_runner_send_main.py:130] INFO 报告路径：D:\mytest\UnittestDemo\reports\result-20241021.html
[2024-10-21_14:43:03] - [run_x_test_runner_send_main.py:251] INFO main start...
[2024-10-21_14:43:04] - [run_x_test_runner_send_main.py:61] CRITICAL test_excel_api (unittest.loader._FailedTest.test_excel_api)
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 589, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\loader.py", line 33, in testFailure
    raise self._exception
ImportError: Failed to import test module: test_excel_api
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\loader.py", line 396, in _find_test_path
    module = self._get_module_from_name(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\loader.py", line 339, in _get_module_from_name
    __import__(name)
  File "D:\mytest\UnittestDemo\testcase\test_excel_api.py", line 16, in <module>
    from utils import verification_code_login
  File "D:\mytest\UnittestDemo\utils\verification_code_login.py", line 12, in <module>
    import muggle_ocr
  File "D:\mytest\UnittestDemo\muggle_ocr\__init__.py", line 5, in <module>
    from muggle_ocr.sdk import SDK
  File "D:\mytest\UnittestDemo\muggle_ocr\sdk.py", line 14, in <module>
    import tensorflow as tf
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\__init__.py", line 47, in <module>
    from tensorflow._api.v2 import __internal__
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\_api\v2\__internal__\__init__.py", line 11, in <module>
    from tensorflow._api.v2.__internal__ import distribute
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\_api\v2\__internal__\distribute\__init__.py", line 8, in <module>
    from tensorflow._api.v2.__internal__.distribute import combinations
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\_api\v2\__internal__\distribute\combinations\__init__.py", line 8, in <module>
    from tensorflow.python.distribute.combinations import env # line: 456
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\distribute\combinations.py", line 33, in <module>
    from tensorflow.python.distribute import collective_all_reduce_strategy
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\distribute\collective_all_reduce_strategy.py", line 25, in <module>
    from tensorflow.python.distribute import cross_device_ops as cross_device_ops_lib
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\distribute\cross_device_ops.py", line 28, in <module>
    from tensorflow.python.distribute import cross_device_utils
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\distribute\cross_device_utils.py", line 22, in <module>
    from tensorflow.python.distribute import values as value_lib
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\distribute\values.py", line 23, in <module>
    from tensorflow.python.distribute import distribute_lib
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\distribute\distribute_lib.py", line 205, in <module>
    from tensorflow.python.data.ops import dataset_ops
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\data\__init__.py", line 21, in <module>
    from tensorflow.python.data import experimental
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\data\experimental\__init__.py", line 98, in <module>
    from tensorflow.python.data.experimental import service
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\data\experimental\service\__init__.py", line 419, in <module>
    from tensorflow.python.data.experimental.ops.data_service_ops import distribute
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\data\experimental\ops\data_service_ops.py", line 23, in <module>
    from tensorflow.python.data.experimental.ops import compression_ops
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\data\experimental\ops\compression_ops.py", line 16, in <module>
    from tensorflow.python.data.util import structure
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\data\util\structure.py", line 32, in <module>
    from tensorflow.python.ops.ragged import ragged_tensor
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\ragged\__init__.py", line 28, in <module>
    from tensorflow.python.ops.ragged import ragged_tensor
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\ragged\ragged_tensor.py", line 3149, in <module>
    from tensorflow.python.ops.ragged import ragged_ops  # pylint: disable=unused-import, g-bad-import-order, g-import-not-at-top
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\ragged\ragged_ops.py", line 41, in <module>
    from tensorflow.python.ops.ragged import ragged_image_ops
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\ragged\ragged_image_ops.py", line 24, in <module>
    from tensorflow.python.ops import image_ops
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\image_ops.py", line 159, in <module>
    from tensorflow.python.ops.image_ops_impl import *
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\image_ops_impl.py", line 40, in <module>
    from tensorflow.python.ops import nn_impl
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\nn_impl.py", line 26, in <module>
    from tensorflow.python.ops import ctc_ops  # pylint: disable=unused-import
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\ctc_ops.py", line 32, in <module>
    from tensorflow.python.ops import custom_gradient
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\custom_gradient.py", line 17, in <module>
    from tensorflow.python.eager import backprop
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\eager\backprop.py", line 47, in <module>
    from tensorflow.python.ops.parallel_for import control_flow_ops as pfor_ops
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\parallel_for\control_flow_ops.py", line 37, in <module>
    from tensorflow.python.ops.parallel_for.pfor import PFor
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\parallel_for\pfor.py", line 71, in <module>
    from tensorflow.python.platform import flags
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\platform\flags.py", line 121, in <module>
    FLAGS = _FlagValuesWrapper(FLAGS)  # pylint: disable=used-before-assignment
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "_pydevd_bundle\\pydevd_pep_669_tracing_cython.pyx", line 504, in _pydevd_bundle.pydevd_pep_669_tracing_cython.PyRaiseCallback.__call__
  File "_pydevd_bundle\\pydevd_pep_669_tracing_cython.pyx", line 47, in _pydevd_bundle.pydevd_pep_669_tracing_cython.PEP669CallbackBase.frame
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\platform\flags.py", line 73, in __getattribute__
    return self.__dict__['__wrapped'].__getattribute__(name)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: '__wrapped'

[2024-10-21_14:43:04] - [run_x_test_runner_send_main.py:130] INFO 报告路径：D:\mytest\UnittestDemo\reports\result-20241021.html
[2024-10-21_14:48:19] - [run_x_test_runner_send_main.py:251] INFO main start...
[2024-10-21_14:48:20] - [run_x_test_runner_send_main.py:61] CRITICAL test_excel_api (unittest.loader._FailedTest.test_excel_api)
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 589, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\loader.py", line 33, in testFailure
    raise self._exception
ImportError: Failed to import test module: test_excel_api
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\loader.py", line 396, in _find_test_path
    module = self._get_module_from_name(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\loader.py", line 339, in _get_module_from_name
    __import__(name)
  File "D:\mytest\UnittestDemo\testcase\test_excel_api.py", line 16, in <module>
    from utils import verification_code_login
  File "D:\mytest\UnittestDemo\utils\verification_code_login.py", line 12, in <module>
    import muggle_ocr
  File "D:\mytest\UnittestDemo\muggle_ocr\__init__.py", line 5, in <module>
    from muggle_ocr.sdk import SDK
  File "D:\mytest\UnittestDemo\muggle_ocr\sdk.py", line 14, in <module>
    import tensorflow as tf
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\__init__.py", line 47, in <module>
    from tensorflow._api.v2 import __internal__
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\_api\v2\__internal__\__init__.py", line 11, in <module>
    from tensorflow._api.v2.__internal__ import distribute
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\_api\v2\__internal__\distribute\__init__.py", line 8, in <module>
    from tensorflow._api.v2.__internal__.distribute import combinations
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\_api\v2\__internal__\distribute\combinations\__init__.py", line 8, in <module>
    from tensorflow.python.distribute.combinations import env # line: 456
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\distribute\combinations.py", line 33, in <module>
    from tensorflow.python.distribute import collective_all_reduce_strategy
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\distribute\collective_all_reduce_strategy.py", line 25, in <module>
    from tensorflow.python.distribute import cross_device_ops as cross_device_ops_lib
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\distribute\cross_device_ops.py", line 28, in <module>
    from tensorflow.python.distribute import cross_device_utils
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\distribute\cross_device_utils.py", line 22, in <module>
    from tensorflow.python.distribute import values as value_lib
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\distribute\values.py", line 23, in <module>
    from tensorflow.python.distribute import distribute_lib
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\distribute\distribute_lib.py", line 205, in <module>
    from tensorflow.python.data.ops import dataset_ops
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\data\__init__.py", line 21, in <module>
    from tensorflow.python.data import experimental
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\data\experimental\__init__.py", line 98, in <module>
    from tensorflow.python.data.experimental import service
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\data\experimental\service\__init__.py", line 419, in <module>
    from tensorflow.python.data.experimental.ops.data_service_ops import distribute
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\data\experimental\ops\data_service_ops.py", line 23, in <module>
    from tensorflow.python.data.experimental.ops import compression_ops
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\data\experimental\ops\compression_ops.py", line 16, in <module>
    from tensorflow.python.data.util import structure
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\data\util\structure.py", line 32, in <module>
    from tensorflow.python.ops.ragged import ragged_tensor
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\ragged\__init__.py", line 28, in <module>
    from tensorflow.python.ops.ragged import ragged_tensor
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\ragged\ragged_tensor.py", line 3149, in <module>
    from tensorflow.python.ops.ragged import ragged_ops  # pylint: disable=unused-import, g-bad-import-order, g-import-not-at-top
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\ragged\ragged_ops.py", line 41, in <module>
    from tensorflow.python.ops.ragged import ragged_image_ops
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\ragged\ragged_image_ops.py", line 24, in <module>
    from tensorflow.python.ops import image_ops
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\image_ops.py", line 159, in <module>
    from tensorflow.python.ops.image_ops_impl import *
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\image_ops_impl.py", line 40, in <module>
    from tensorflow.python.ops import nn_impl
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\nn_impl.py", line 26, in <module>
    from tensorflow.python.ops import ctc_ops  # pylint: disable=unused-import
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\ctc_ops.py", line 32, in <module>
    from tensorflow.python.ops import custom_gradient
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\custom_gradient.py", line 17, in <module>
    from tensorflow.python.eager import backprop
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\eager\backprop.py", line 47, in <module>
    from tensorflow.python.ops.parallel_for import control_flow_ops as pfor_ops
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\parallel_for\control_flow_ops.py", line 37, in <module>
    from tensorflow.python.ops.parallel_for.pfor import PFor
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\parallel_for\pfor.py", line 71, in <module>
    from tensorflow.python.platform import flags
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\platform\flags.py", line 121, in <module>
    FLAGS = _FlagValuesWrapper(FLAGS)  # pylint: disable=used-before-assignment
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "_pydevd_bundle\\pydevd_pep_669_tracing_cython.pyx", line 504, in _pydevd_bundle.pydevd_pep_669_tracing_cython.PyRaiseCallback.__call__
  File "_pydevd_bundle\\pydevd_pep_669_tracing_cython.pyx", line 47, in _pydevd_bundle.pydevd_pep_669_tracing_cython.PEP669CallbackBase.frame
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\platform\flags.py", line 73, in __getattribute__
    return self.__dict__['__wrapped'].__getattribute__(name)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: '__wrapped'

[2024-10-21_14:48:20] - [run_x_test_runner_send_main.py:130] INFO 报告路径：D:\mytest\UnittestDemo\reports\result-20241021.html
[2024-10-21_14:48:41] - [run_x_test_runner_send_main.py:251] INFO main start...
[2024-10-21_14:48:44] - [run_x_test_runner_send_main.py:61] CRITICAL test_excel_api (unittest.loader._FailedTest.test_excel_api)
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 589, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\loader.py", line 33, in testFailure
    raise self._exception
ImportError: Failed to import test module: test_excel_api
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\loader.py", line 396, in _find_test_path
    module = self._get_module_from_name(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\loader.py", line 339, in _get_module_from_name
    __import__(name)
  File "D:\mytest\UnittestDemo\testcase\test_excel_api.py", line 16, in <module>
    from utils import verification_code_login
  File "D:\mytest\UnittestDemo\utils\verification_code_login.py", line 12, in <module>
    import muggle_ocr
  File "D:\mytest\UnittestDemo\muggle_ocr\__init__.py", line 5, in <module>
    from muggle_ocr.sdk import SDK
  File "D:\mytest\UnittestDemo\muggle_ocr\sdk.py", line 14, in <module>
    import tensorflow as tf
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\__init__.py", line 47, in <module>
    from tensorflow._api.v2 import __internal__
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\_api\v2\__internal__\__init__.py", line 11, in <module>
    from tensorflow._api.v2.__internal__ import distribute
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\_api\v2\__internal__\distribute\__init__.py", line 8, in <module>
    from tensorflow._api.v2.__internal__.distribute import combinations
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\_api\v2\__internal__\distribute\combinations\__init__.py", line 8, in <module>
    from tensorflow.python.distribute.combinations import env # line: 456
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\distribute\combinations.py", line 33, in <module>
    from tensorflow.python.distribute import collective_all_reduce_strategy
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\distribute\collective_all_reduce_strategy.py", line 25, in <module>
    from tensorflow.python.distribute import cross_device_ops as cross_device_ops_lib
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\distribute\cross_device_ops.py", line 28, in <module>
    from tensorflow.python.distribute import cross_device_utils
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\distribute\cross_device_utils.py", line 22, in <module>
    from tensorflow.python.distribute import values as value_lib
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\distribute\values.py", line 23, in <module>
    from tensorflow.python.distribute import distribute_lib
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\distribute\distribute_lib.py", line 205, in <module>
    from tensorflow.python.data.ops import dataset_ops
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\data\__init__.py", line 21, in <module>
    from tensorflow.python.data import experimental
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\data\experimental\__init__.py", line 98, in <module>
    from tensorflow.python.data.experimental import service
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\data\experimental\service\__init__.py", line 419, in <module>
    from tensorflow.python.data.experimental.ops.data_service_ops import distribute
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\data\experimental\ops\data_service_ops.py", line 23, in <module>
    from tensorflow.python.data.experimental.ops import compression_ops
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\data\experimental\ops\compression_ops.py", line 16, in <module>
    from tensorflow.python.data.util import structure
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\data\util\structure.py", line 32, in <module>
    from tensorflow.python.ops.ragged import ragged_tensor
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\ragged\__init__.py", line 28, in <module>
    from tensorflow.python.ops.ragged import ragged_tensor
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\ragged\ragged_tensor.py", line 3149, in <module>
    from tensorflow.python.ops.ragged import ragged_ops  # pylint: disable=unused-import, g-bad-import-order, g-import-not-at-top
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\ragged\ragged_ops.py", line 41, in <module>
    from tensorflow.python.ops.ragged import ragged_image_ops
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\ragged\ragged_image_ops.py", line 24, in <module>
    from tensorflow.python.ops import image_ops
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\image_ops.py", line 159, in <module>
    from tensorflow.python.ops.image_ops_impl import *
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\image_ops_impl.py", line 40, in <module>
    from tensorflow.python.ops import nn_impl
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\nn_impl.py", line 26, in <module>
    from tensorflow.python.ops import ctc_ops  # pylint: disable=unused-import
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\ctc_ops.py", line 32, in <module>
    from tensorflow.python.ops import custom_gradient
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\custom_gradient.py", line 17, in <module>
    from tensorflow.python.eager import backprop
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\eager\backprop.py", line 47, in <module>
    from tensorflow.python.ops.parallel_for import control_flow_ops as pfor_ops
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\parallel_for\control_flow_ops.py", line 37, in <module>
    from tensorflow.python.ops.parallel_for.pfor import PFor
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\parallel_for\pfor.py", line 71, in <module>
    from tensorflow.python.platform import flags
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\platform\flags.py", line 121, in <module>
    FLAGS = _FlagValuesWrapper(FLAGS)  # pylint: disable=used-before-assignment
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "_pydevd_bundle\\pydevd_pep_669_tracing_cython.pyx", line 504, in _pydevd_bundle.pydevd_pep_669_tracing_cython.PyRaiseCallback.__call__
  File "_pydevd_bundle\\pydevd_pep_669_tracing_cython.pyx", line 47, in _pydevd_bundle.pydevd_pep_669_tracing_cython.PEP669CallbackBase.frame
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\platform\flags.py", line 73, in __getattribute__
    return self.__dict__['__wrapped'].__getattribute__(name)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: '__wrapped'

[2024-10-21_14:48:44] - [run_x_test_runner_send_main.py:130] INFO 报告路径：D:\mytest\UnittestDemo\reports\result-20241021.html
[2024-10-21_14:50:41] - [run_x_test_runner_send_main.py:251] INFO main start...
[2024-10-21_14:50:42] - [run_x_test_runner_send_main.py:61] CRITICAL test_excel_api (unittest.loader._FailedTest.test_excel_api)
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 589, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\loader.py", line 33, in testFailure
    raise self._exception
ImportError: Failed to import test module: test_excel_api
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\loader.py", line 396, in _find_test_path
    module = self._get_module_from_name(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\loader.py", line 339, in _get_module_from_name
    __import__(name)
  File "D:\mytest\UnittestDemo\testcase\test_excel_api.py", line 16, in <module>
    from utils import verification_code_login
  File "D:\mytest\UnittestDemo\utils\verification_code_login.py", line 12, in <module>
    import muggle_ocr
  File "D:\mytest\UnittestDemo\muggle_ocr\__init__.py", line 5, in <module>
    from muggle_ocr.sdk import SDK
  File "D:\mytest\UnittestDemo\muggle_ocr\sdk.py", line 14, in <module>
    import tensorflow as tf
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\__init__.py", line 47, in <module>
    from tensorflow._api.v2 import __internal__
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\_api\v2\__internal__\__init__.py", line 11, in <module>
    from tensorflow._api.v2.__internal__ import distribute
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\_api\v2\__internal__\distribute\__init__.py", line 8, in <module>
    from tensorflow._api.v2.__internal__.distribute import combinations
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\_api\v2\__internal__\distribute\combinations\__init__.py", line 8, in <module>
    from tensorflow.python.distribute.combinations import env # line: 456
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\distribute\combinations.py", line 33, in <module>
    from tensorflow.python.distribute import collective_all_reduce_strategy
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\distribute\collective_all_reduce_strategy.py", line 25, in <module>
    from tensorflow.python.distribute import cross_device_ops as cross_device_ops_lib
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\distribute\cross_device_ops.py", line 28, in <module>
    from tensorflow.python.distribute import cross_device_utils
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\distribute\cross_device_utils.py", line 22, in <module>
    from tensorflow.python.distribute import values as value_lib
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\distribute\values.py", line 23, in <module>
    from tensorflow.python.distribute import distribute_lib
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\distribute\distribute_lib.py", line 205, in <module>
    from tensorflow.python.data.ops import dataset_ops
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\data\__init__.py", line 21, in <module>
    from tensorflow.python.data import experimental
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\data\experimental\__init__.py", line 98, in <module>
    from tensorflow.python.data.experimental import service
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\data\experimental\service\__init__.py", line 419, in <module>
    from tensorflow.python.data.experimental.ops.data_service_ops import distribute
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\data\experimental\ops\data_service_ops.py", line 23, in <module>
    from tensorflow.python.data.experimental.ops import compression_ops
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\data\experimental\ops\compression_ops.py", line 16, in <module>
    from tensorflow.python.data.util import structure
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\data\util\structure.py", line 32, in <module>
    from tensorflow.python.ops.ragged import ragged_tensor
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\ragged\__init__.py", line 28, in <module>
    from tensorflow.python.ops.ragged import ragged_tensor
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\ragged\ragged_tensor.py", line 3149, in <module>
    from tensorflow.python.ops.ragged import ragged_ops  # pylint: disable=unused-import, g-bad-import-order, g-import-not-at-top
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\ragged\ragged_ops.py", line 41, in <module>
    from tensorflow.python.ops.ragged import ragged_image_ops
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\ragged\ragged_image_ops.py", line 24, in <module>
    from tensorflow.python.ops import image_ops
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\image_ops.py", line 159, in <module>
    from tensorflow.python.ops.image_ops_impl import *
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\image_ops_impl.py", line 40, in <module>
    from tensorflow.python.ops import nn_impl
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\nn_impl.py", line 26, in <module>
    from tensorflow.python.ops import ctc_ops  # pylint: disable=unused-import
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\ctc_ops.py", line 32, in <module>
    from tensorflow.python.ops import custom_gradient
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\custom_gradient.py", line 17, in <module>
    from tensorflow.python.eager import backprop
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\eager\backprop.py", line 47, in <module>
    from tensorflow.python.ops.parallel_for import control_flow_ops as pfor_ops
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\parallel_for\control_flow_ops.py", line 37, in <module>
    from tensorflow.python.ops.parallel_for.pfor import PFor
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\ops\parallel_for\pfor.py", line 71, in <module>
    from tensorflow.python.platform import flags
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\platform\flags.py", line 121, in <module>
    FLAGS = _FlagValuesWrapper(FLAGS)  # pylint: disable=used-before-assignment
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "_pydevd_bundle\\pydevd_pep_669_tracing_cython.pyx", line 504, in _pydevd_bundle.pydevd_pep_669_tracing_cython.PyRaiseCallback.__call__
  File "_pydevd_bundle\\pydevd_pep_669_tracing_cython.pyx", line 47, in _pydevd_bundle.pydevd_pep_669_tracing_cython.PEP669CallbackBase.frame
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\python\platform\flags.py", line 73, in __getattribute__
    return self.__dict__['__wrapped'].__getattribute__(name)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: '__wrapped'

[2024-10-21_14:50:42] - [run_x_test_runner_send_main.py:130] INFO 报告路径：D:\mytest\UnittestDemo\reports\result-20241021.html
[2024-10-21_14:51:00] - [run_x_test_runner_send_main.py:251] INFO main start...
[2024-10-21_14:51:01] - [test_excel_api.py:175] INFO /test-api/system/applet/feedback/backend/list 响应数据：{"code":401,"msg":"登录状态已过期"}
[2024-10-21_14:51:01] - [test_excel_api.py:191] WARNING 请求参数：{"pageNo":1,"pageSize":10,"appUserName":"用户188****7806","replyStatus":0}
[2024-10-21_14:51:01] - [run_x_test_runner_send_main.py:56] ERROR test_api_1 (test_excel_api.TestAPI.test_api_1)
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 589, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\ddt.py", line 221, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mytest\UnittestDemo\testcase\test_excel_api.py", line 192, in test_api
    raise e
  File "D:\mytest\UnittestDemo\testcase\test_excel_api.py", line 187, in test_api
    self.assertIn(msg, response.content.decode("utf-8"), f"{case_id} {title} {url}")
AssertionError: '测试反馈内容' not found in '{"code":401,"msg":"登录状态已过期"}' : lqc_17 查询根据用户名查询没有回复的记录 /test-api/system/applet/feedback/backend/list
[2024-10-21_14:51:01] - [test_excel_api.py:175] INFO /test-api/policylibrary/policy/crawlData/select 响应数据：{"code":401,"msg":"登录状态已过期"}
[2024-10-21_14:51:01] - [test_excel_api.py:191] WARNING 请求参数：{"pageSize":10,"pageNo":1,"markStatus":6}
[2024-10-21_14:51:01] - [run_x_test_runner_send_main.py:56] ERROR test_api_2 (test_excel_api.TestAPI.test_api_2)
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 589, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\ddt.py", line 221, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mytest\UnittestDemo\testcase\test_excel_api.py", line 192, in test_api
    raise e
  File "D:\mytest\UnittestDemo\testcase\test_excel_api.py", line 187, in test_api
    self.assertIn(msg, response.content.decode("utf-8"), f"{case_id} {title} {url}")
AssertionError: '"code":200' not found in '{"code":401,"msg":"登录状态已过期"}' : lqc_24 查询无效数据 /test-api/policylibrary/policy/crawlData/select
[2024-10-21_14:51:01] - [test_excel_api.py:255] INFO 变量替换：variable2 => None
[2024-10-21_14:51:01] - [test_excel_api.py:175] INFO /test-api/policylibrary/policy/crawlData/back/${variable2} 响应数据：{"code":401,"msg":"登录状态已过期"}
[2024-10-21_14:51:01] - [test_excel_api.py:191] WARNING 请求参数：None
[2024-10-21_14:51:01] - [run_x_test_runner_send_main.py:56] ERROR test_api_3 (test_excel_api.TestAPI.test_api_3)
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\unittest\case.py", line 589, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\ddt.py", line 221, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mytest\UnittestDemo\testcase\test_excel_api.py", line 192, in test_api
    raise e
  File "D:\mytest\UnittestDemo\testcase\test_excel_api.py", line 187, in test_api
    self.assertIn(msg, response.content.decode("utf-8"), f"{case_id} {title} {url}")
AssertionError: '"code":200' not found in '{"code":401,"msg":"登录状态已过期"}' : lqc_25 恢复用户释放成无效状态的数据 /test-api/policylibrary/policy/crawlData/back/${variable2}
[2024-10-21_14:51:01] - [run_x_test_runner_send_main.py:130] INFO 报告路径：D:\mytest\UnittestDemo\reports\result-20241021.html
[2024-10-21_15:11:21] - [run_x_test_runner_send_main.py:251] INFO main start...
[2024-10-21_15:11:22] - [verification_code_login.py:221] INFO 11 {'code': 500, 'msg': '验证码错误'}
[2024-10-21_15:11:24] - [verification_code_login.py:265] INFO 登录成功 {'Content-Type': 'application/json;charset=utf-8', 'authorization': 'Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyRGVwdElkIjoxMDMsInVzZXJfaWQiOjEsInVzZXJfa2V5IjoiMjYwNmYxMDktZDg2OC00N2RhLWE5MTctMTE3YWI4OWQ0ZTAzIiwidXNlcm5hbWUiOiJhZG1pbiJ9.AQFwLULW7sSBuPEr6N_jlZcmWXi5jghxC08p5Xw2fWYRYGAG5zge3us2xM0koDnWn-c824taw995mfYgPkCa8A'}
[2024-10-21_15:11:24] - [test_excel_api.py:276] INFO 提取变量：1 => 1848244063521959937
[2024-10-21_15:11:24] - [test_excel_api.py:175] INFO /test-api/system/applet/feedback/backend/list 响应数据：{"code":200,"msg":"Success","data":{"page":1,"size":10,"total":2,"list":[{"id":"1848244063521959937","appUserId":"1840678944340381697","appUserName":"用户188****7806","appUserSubmitName":"用户188****7806","appUserPhone":"18813537806","submitIssueType":1,"submitIssueDescription":"测试反馈内容","submitIssueTime":"2024-10-21 14:04:58","uploadImageUrl":"https://lqc-public-oss-pre.oss-cn-shenzhen.aliyuncs.com/test/lqc-app/c5c931dadc424b71a60326da53828fb6.jpg","replyStatus":0,"replyText":null,"replyTime":null,"replyerName":"启程智远"},{"id":"1847543017367629825","appUserId":"1840678944340381697","appUserName":"用户188****7806","appUserSubmitName":"用户188****7806","appUserPhone":"18813537806","submitIssueType":1,"submitIssueDescription":"你看看吧，","submitIssueTime":"2024-10-19 15:39:15","uploadImageUrl":"https://lqc-public-oss-pre.oss-cn-shenzhen.aliyuncs.com/test/lqc-app/9efcddd7ff1a4f73993ff485bd423fb7.jpg","replyStatus":0,"replyText":null,"replyTime":null,"replyerName":"启程智远"}]}}
[2024-10-21_15:11:25] - [test_excel_api.py:276] INFO 提取变量：2 => 59203
[2024-10-21_15:11:25] - [test_excel_api.py:175] INFO /test-api/policylibrary/policy/crawlData/select 响应数据：{"code":200,"msg":"Success","data":{"page":1,"size":10,"total":2,"list":[{"crawlDataId":59203,"title":"关于举行湛山创客工厂第十三批入驻企业答辩评审会的通知","originText":null,"crawlDataMd5":"aa55470cdae56972945af7ea69d99a77","url":"https://hrss.qingdao.gov.cn/zxzx_47/tzgg_47/202206/t20220617_6174033.shtml","dumpBusinessId":null,"crawlFileList":null,"dumpStatus":0,"dumpStatusName":"未转存","dumpType":null,"dumpTypeName":null,"officialPublishTime":"2020-07-24 00:00:00","crawlTime":"2024-04-28 12:00:00","rank":1,"rankName":"国家级","provinceCode":null,"provinceName":null,"cityCode":null,"cityName":null,"areaCode":null,"areaName":null,"deptId":null,"deptName":null,"phone":null,"address":null,"categoryVOList":null,"projectBaseInfoVO":null,"checkTime":null,"checkerId":null,"checkerName":null,"markerName":"启程智远","markerId":1,"markStatus":6,"markTime":"2024-09-24 16:14:01","recognizeType":6,"recognizeTypeVal":null},{"crawlDataId":59178,"title":"关于停止水平评价类技能人员职业资格证书发放工作的通知","originText":null,"crawlDataMd5":"78921fb1a3ff24d663f22383c157756e","url":"https://hrss.qingdao.gov.cn/zxzx_47/tzgg_47/202206/t20220613_6137909.shtml","dumpBusinessId":null,"crawlFileList":null,"dumpStatus":0,"dumpStatusName":"未转存","dumpType":null,"dumpTypeName":null,"officialPublishTime":"2022-03-21 00:00:00","crawlTime":"2024-04-28 12:00:00","rank":1,"rankName":"国家级","provinceCode":null,"provinceName":null,"cityCode":null,"cityName":null,"areaCode":null,"areaName":null,"deptId":null,"deptName":null,"phone":null,"address":null,"categoryVOList":null,"projectBaseInfoVO":null,"checkTime":null,"checkerId":null,"checkerName":null,"markerName":"启程智远","markerId":1,"markStatus":6,"markTime":"2024-09-25 16:30:37","recognizeType":6,"recognizeTypeVal":null}]}}
[2024-10-21_15:11:25] - [test_excel_api.py:255] INFO 变量替换：variable2 => 59203
[2024-10-21_15:11:25] - [test_excel_api.py:175] INFO /test-api/policylibrary/policy/crawlData/back/${variable2} 响应数据：{"code":200,"msg":null,"data":null}
[2024-10-21_15:11:25] - [run_x_test_runner_send_main.py:130] INFO 报告路径：D:\mytest\UnittestDemo\reports\result-20241021.html
